TASK-141 Adds pouchdb
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #125
Opened 2020-12-17 05:13 UTC by Qwebeck

Zestawienie pouchdb i electrona. 
Obecnie to działa w taki sposób, że przy uruchomieniu aplikacja sprawdza w bazie czy jest grafik z aktualnego miesiąca. 
W przypadku jeżeli tak, to wczytuje go, w przypadku jeżeli nie - to zostawia pusty ekran.
Żeby można było to przetestować, dodałem do folderu `docs` grafik na grudzień:
potrzeba go wczytać przejść na zakładkę edycji i kliknąć przycisk zapisz.

2020-12-17 05:30 UTC, Qwebeck commented on src/api/local-storage-provider.model.ts
> +/*eslint-disable @typescript-eslint/camelcase */
Używam tutaj `grafiku`, więc musiałem zdisablować `camelcase`

2020-12-17 05:30 UTC, Qwebeck commented on src/api/local-storage-provider.model.ts
> +      const revisions = await this.storage.allDocs({ include_docs: true });
Wiem, że dziwnie wygląda: pobieranie wszystkich dokumentów z bazy, ale to jest polecana w dokumentacji metoda do napisania zapytań.
Ale teraz zacząłem się zastanawiać i pewnie coś źle rozumiem, więc jeszcze o tym doczytam
https://pouchdb.com/guides/bulk-operations.html#please-use-alldocs

2020-12-17 05:30 UTC, Qwebeck commented on src/components/schedule-page/edit-page/edit-page-toolbar.component.tsx
> +import { Link } from "react-router-dom";
Najpierw myślałem, że bedę potrzebować takiego podziału, żeby w wygodny czytelny sposób umieścić `context` na poziomie całej strony, a nie tylko jednego komponentu
Potem zrozumiałem, że nie, ale nie chciałem cofać tych zmian, bo moim zdaniem, na pewno nie przeszkodzą

2020-12-17 05:30 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule.component.tsx
> +  const { schedule: scheduleLocalState } = useContext(ScheduleLogicContext);
To jest inna składnia do dekonstrukcji obiektów. 
`{ key: newVariableName }`
Używam tego tutaj, bo w związku z tym, że wyniosłem context wyżej, musiałem też rozszerzyć o dodatkowe ( właśnie to pod którym piszę ten komentarz ) pole

2020-12-17 11:04 UTC, pectom commented
Niestety nie udało mi się tego odpalić. Myślałem, że to tylko u mnie bo builduje się w CI, ale u @maciekb05 też jest taki problem.  
![image](https://user-images.githubusercontent.com/23723122/102479957-ea2fbd00-405f-11eb-8fac-5c53ea898bdf.png)

2020-12-18 13:14 UTC, VVlovsky requested changes
Niestety mam coś takiego :c
![image](https://user-images.githubusercontent.com/36051968/102618465-88488380-4143-11eb-8471-fa3c3f572677.png)

2020-12-19 14:51 UTC, Qwebeck commented
Proponuję żebyśmy zdwonili się dzisiaj około 21:30 i razem przez to przeszli, bo tak będzie szybciej

2020-12-19 21:11 UTC, Qwebeck commented on src/api/persistance-store.model.ts
> +  abstract getShifts(period: ScheduleKey): ThunkFunction<ShiftModel>;
Usunąć

2020-12-19 21:38 UTC, VVlovsky approved these changes
Super praca :+1:

2020-12-20 00:00 UTC, pectom approved these changes

2020-12-20 00:00 UTC, merged