Add styling of edit/add worker component inside drawer
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #128
Opened 2020-12-18 21:26 UTC by maciekb05

https://www.figma.com/file/YJhIgkm7AHuBIOOaHBCaql/NSP?node-id=0%3A1

Drawer w dwóch podobnych wersjach:
dodawanie pracownika (bez części zmiany spoko i niespoko)
edycja pracownika
jeśli chodzi o wymiar pracy, to select Umowa ma dwie opcje UoP i Zlecenie. Dla UoP pojawia się po prawej select z dwoma ułamkami etatu (1/1 i 1/2 oraz opcja inne, która pozwala na wpisanie innego ułamka), dla zlecenia pole do wpisania godzin do wyrobienia w miesiącu (wpisanie ułamka Tomek już robił)
UoP i zlecenia mają być konwertowalne, czyli po zmianie typu umowy, ma automatycznie ustawić się odpowiednia ilość godzin/ułamek

2020-12-18 21:28 UTC, maciekb05 commented
Na razie wrzucam same style zawartości drawera, bez funkcjonalności/ faktycznego zapisu/update'u

2020-12-19 13:24 UTC, Qwebeck commented on src/components/namestable/worker-edit.helper.tsx
> +}
Mamy taką funkcję w `StringHelper`.
![image](https://user-images.githubusercontent.com/21079319/102689993-ba6cea80-4202-11eb-9640-5118808a9a8c.png)

2020-12-19 14:55 UTC, maciekb05 commented on src/common-models/worker-info.model.ts
> +  CONTRACTOR = "CONTRACTOR",
tak, zmienię na employment contract i civil contract

2020-12-19 22:18 UTC, pectom requested changes
Nie przechodzi testu

2020-12-22 09:07 UTC, Dimonium-239 commented
Nie wiem czy to będzie miało wpływ na testy, ponieważ u mnie, przechodzą zarówno jak przed zmianami tak i po zmianach w tym miejscu. 
![image](https://user-images.githubusercontent.com/34006606/102869722-5a618880-443c-11eb-8a5d-f0ca5eac4271.png)
Ale te zmiany robią z tego:
![image](https://user-images.githubusercontent.com/34006606/102870303-25096a80-443d-11eb-999d-0a0ab9d93494.png)
To:
![image](https://user-images.githubusercontent.com/34006606/102870373-3d798500-443d-11eb-83a7-3d1fee5bf152.png)
Przy tym wszystko działa poprawnie w zakładce 'Edytuj'

2020-12-22 09:11 UTC, maciekb05 commented
> Nie wiem czy to będzie miało wpływ na testy, ponieważ u mnie, przechodzą zarówno jak przed zmianami tak i po zmianach w tym miejscu.
> ![image](https://user-images.githubusercontent.com/34006606/102869722-5a618880-443c-11eb-8a5d-f0ca5eac4271.png)
> Ale te zmiany robią z tego:
> ![image](https://user-images.githubusercontent.com/34006606/102870303-25096a80-443d-11eb-999d-0a0ab9d93494.png)
> To:
> ![image](https://user-images.githubusercontent.com/34006606/102870373-3d798500-443d-11eb-83a7-3d1fee5bf152.png)
> Przy tym wszystko działa poprawnie w zakładce 'Edytuj'

Jakbyś mógł dodać commita tutaj, albo zrobić sobie PR'a zależnego od tego co tutaj i zobaczyć czy CI przechodzi, to byłbym bardzo wdzięczny

2020-12-22 10:28 UTC, Qwebeck commented on src/components/workers-page/workers-tab/worker-drawer.component.tsx
> +  const isEdit = mode === WorkerDrawerMode.EDIT;
@maciekb05 
Na razie w celach developmentu można ustawić w tym miejscu na sztywno `EditMode`

https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend/blob/b3cd626e7e08318b7a0c3a3f3433ddb9b6c195c5/src/components/namestable/nametable-section.component.tsx#L19

Ja będę wprowadzać teraz te dwa róźne tryby i dodam jakieś rozrózróźnienie między nimi

2021-01-02 12:57 UTC, maciekb05 commented
W tym zadaniu trzeba jeszcze w sumie dograć sytuację Bohdan/Tomek mówi że formularz ma działać tak jak działa VS Paweł mówi, że ma działać dokładnie jak na designach.

2021-01-02 12:59 UTC, maciekb05 commented
A tak to dodatkowo trzeba zrobić takie taski:
- Dodać translację godzin na wersję ułamków etatu + unit testy
- Zapisywanie w edycji w stanie
- Dograć do końca działanie przycisku NEW (na razie zajmowałem się tylko edit) (możliwe, że to będzie bardzo proste)

2021-01-02 14:02 UTC, pectom commented
Sypie bardzo dużo warningów z lintera: 
![image](https://user-images.githubusercontent.com/23723122/103458767-84a02980-4d0b-11eb-8009-99803c7fa061.png)

2021-01-02 14:04 UTC, pectom commented
Maska działa źle:
![image](https://user-images.githubusercontent.com/23723122/103458781-b0231400-4d0b-11eb-8882-befea8d8d459.png)
![image](https://user-images.githubusercontent.com/23723122/103458789-b913e580-4d0b-11eb-9a93-f03956971b01.png)

2021-01-02 14:26 UTC, pectom requested changes

2021-01-02 14:26 UTC, pectom commented on src/components/namestable/worker-edit.component.tsx
> +    updateWorkerInfo(target.name, target.value);
Imo tak jest ładniej 
``` typescript
 function handleUpdate(event) {
    const { name, value } = event.target;
    updateWorkerInfo(name, value);
  }
  ```

2021-01-02 14:26 UTC, pectom commented on src/components/namestable/worker-edit.component.tsx
> +function TextMaskCustom(props: TextMaskCustomProps) {
Taki komponent dałbym do folderu ze wspólnymi komponentami, bo może gdzieś będziemy tego reużywać

2021-01-02 14:26 UTC, pectom commented on src/components/namestable/worker-edit.helper.tsx
> +export function translateAndCapitalizeWorkerType(workerType: WorkerType): string {
Nie umieszczamy helperów  w komponentach. Jeśli kod jest wykorzystywany w jednym komponencie to dodajemy go tylko tam. Jeśli może pojawić się potrzeba ponownego wykorzystania to należy to wrzucić do folderu jakiegoś istniejącego helpera z helpers albo dodać nowego. 
Dodatkowo ten kod dla translateAndCapitalizeWorkerType oraz translateAndCapitalizeContractType  jest powtórzony. Można stworzyć jedną generyczną funkcję - translateAndCapitalize, która przyjmuje 2 parametry: pierwszy to helper, a drugi coś co helper może przetłumaczyć.

2021-01-02 14:34 UTC, pectom commented
> W tym zadaniu trzeba jeszcze w sumie dograć sytuację Bohdan/Tomek mówi że formularz ma działać tak jak działa VS Paweł mówi, że ma działać dokładnie jak na designach.

Już nie pamiętam jak to ustalaliśmy w końcu i nie jakie były argumenty za tym, żeby to miało być zrobione tak jak teraz. Z tego co patrzę na obecną wersję na Figmie to moim zdaniem jest to lepiej zrobione niż tutaj i będzie to wygodniejsze dla pielęgniarki. Będzie mogła sobie wybrać z dropdowna z tych najbardziej popularnych etatów, a nie będzie to też wymagało od nas jakoś bardzo dużo pracy,  więc ja chciałbym żebyśmy jednak trzymali się tego co na Figmie. 
@Qwebeck @prenc co wy na to?

2021-01-02 14:36 UTC, pectom commented
> A tak to dodatkowo trzeba zrobić takie taski:
> 
> * Dodać translację godzin na wersję ułamków etatu + unit testy
> * Zapisywanie w edycji w stanie
> * Dograć do końca działanie przycisku NEW (na razie zajmowałem się tylko edit) (możliwe, że to będzie bardzo proste)

Ok to dodaj takie taski jak uważasz (tytuł i opis), żeby nie bylo niepotrzebnych niejaśności. My je przypiszemy do odpowiednich wymagań i ustawimy effort

2021-01-02 15:52 UTC, prenc commented
> > W tym zadaniu trzeba jeszcze w sumie dograć sytuację Bohdan/Tomek mówi że formularz ma działać tak jak działa VS Paweł mówi, że ma działać dokładnie jak na designach.
> 
> Już nie pamiętam jak to ustalaliśmy w końcu i nie jakie były argumenty za tym, żeby to miało być zrobione tak jak teraz. Z tego co patrzę na obecną wersję na Figmie to moim zdaniem jest to lepiej zrobione niż tutaj i będzie to wygodniejsze dla pielęgniarki. Będzie mogła sobie wybrać z dropdowna z tych najbardziej popularnych etatów, a nie będzie to też wymagało od nas jakoś bardzo dużo pracy, więc ja chciałbym żebyśmy jednak trzymali się tego co na Figmie.
> @Qwebeck @prenc co wy na to?

Nas interesuje tylko pełna nazwa.

2021-01-02 15:56 UTC, prenc commented
> > A tak to dodatkowo trzeba zrobić takie taski:
> > 
> > * Dodać translację godzin na wersję ułamków etatu + unit testy
> > * Zapisywanie w edycji w stanie
> > * Dograć do końca działanie przycisku NEW (na razie zajmowałem się tylko edit) (możliwe, że to będzie bardzo proste)
> 
> Ok to dodaj takie taski jak uważasz (tytuł i opis), żeby nie bylo niepotrzebnych niejaśności. My je przypiszemy do odpowiednich wymagań i ustawimy effort



> > W tym zadaniu trzeba jeszcze w sumie dograć sytuację Bohdan/Tomek mówi że formularz ma działać tak jak działa VS Paweł mówi, że ma działać dokładnie jak na designach.
> 
> Już nie pamiętam jak to ustalaliśmy w końcu i nie jakie były argumenty za tym, żeby to miało być zrobione tak jak teraz. Z tego co patrzę na obecną wersję na Figmie to moim zdaniem jest to lepiej zrobione niż tutaj i będzie to wygodniejsze dla pielęgniarki. Będzie mogła sobie wybrać z dropdowna z tych najbardziej popularnych etatów, a nie będzie to też wymagało od nas jakoś bardzo dużo pracy, więc ja chciałbym żebyśmy jednak trzymali się tego co na Figmie.
> @Qwebeck @prenc co wy na to?

Takie dyskusje zostawmy sobie na "standup", na razie zrób to co możesz, bo to czy robić imie i nazwisko osobno czy razem to pierdoła.

2021-01-05 21:23 UTC, pectom approved these changes

2021-01-05 21:30 UTC, merged