Task 161 wysuwanie drawera edycji pracownika
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #136
Opened 2021-01-02 11:07 UTC by maciekb05

2021-01-02 11:39 UTC, pectom commented
@maciekb05  jest z konflikt z developem

2021-01-02 13:27 UTC, pectom requested changes
Dalej jest problem z testem :(

2021-01-05 18:05 UTC, maciekb05 commented
> Dalej jest problem z testem :(

Naprawione

2021-01-05 21:25 UTC, pectom approved these changes

2021-01-05 21:45 UTC, pectom commented
@maciekb05 domergowałem poprzedniego PR i mmay konflikt :(

2021-01-06 21:39 UTC, Qwebeck approved these changes

2021-01-08 17:28 UTC, merged