Task 178 continue
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #150
Opened 2021-01-09 03:18 UTC by Dushess0

Teraz możliwe jest kopiowanie z poprzedniego miesiąca, albo z następnego (jeżeli cofamy się).

2021-01-09 11:52 UTC, pectom commented
Zostało jeszcze dodać akcję wczytywania grafiku z przycisku na środku ekranu

2021-01-09 11:56 UTC, pectom commented
Przy wejściu do aplikajci brakuje switcha do zmiany miesiąca. Powinien on zawierać aktualny miesiąc i umożliwijać zmianę na dowolny.

2021-01-09 12:13 UTC, Qwebeck commented
Można też dodać atrybut `disabled` na przycisk do koppiowania po zmergowaniu tego

https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend/pull/147

2021-01-15 19:34 UTC, pectom requested changes
To co wcześniej pisaliśmy z @Qwebeck

2021-01-17 13:07 UTC, Dushess0 commented
Jeżeli nie ma wczytanego planu to jest wyświetlany obecny miesiąc oraz możemy nawigować się.
![image](https://user-images.githubusercontent.com/44201461/104843761-99182080-58cc-11eb-803c-10f9b685ef75.png)

Przycisk "wgraj z pliku" teraz działa
![image](https://user-images.githubusercontent.com/44201461/104843784-afbe7780-58cc-11eb-9190-5cfdf2cd583a.png)



> > To co wcześniej pisaliśmy z @Qwebeck
> 
> I jeszcze inteligentne przenoszenia zmian (pierwszy wtorek miesiąca z którego kopiujemy powinien się zmapować na pierwszy wtorek miesiąca na który kopiujemy)

miesiąc który jest kopiowany
![image](https://user-images.githubusercontent.com/44201461/104843825-e7c5ba80-58cc-11eb-8647-dd5035a3be53.png)
nowy miesiąć skopiowany z poprzedniego
![image](https://user-images.githubusercontent.com/44201461/104843837-f1e7b900-58cc-11eb-9a31-caf251c38de6.png)

Czyli wtorki są przenoszone na wtorki, poniedziałki na poniedziałki itd.

2021-01-17 15:31 UTC, Qwebeck approved these changes

2021-01-17 15:43 UTC, merged