TASK-193 implemented
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #161
Opened 2021-01-16 01:53 UTC by VVlovsky

2021-01-16 02:33 UTC, Qwebeck requested changes
Generalnie super, ale request changes, ponieważ brakuje przenoszenia pracowników na kolejny miesiąc.

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/employee-info.reducer.ts
> +        return { ...data! };
Lepiej zostawić ten `if` co był poprzednio, ale przenieść go tutaj, ponieważ w reduserze, ty tak naprawdę nie możesz mieć pewności odnośnie tego, czy data nie jest undefindem. A jeśli zrobisz spread `undefined'a`, to polecą errory

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/employee-info.reducer.ts
> +          type: { [action.payload!.worker!.name]: WorkerType.OTHER, ...state.type },
Pewnie zapomniałeś, ale teraz nie uwzględzniasz `WorkerType`

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/employee-info.reducer.ts
> +            ...state.time,
Trochę się czepiam, ale ja bym zrobił dekonstrukcję wyżej, ponieważ tak moim zdaniem będzie czytelniej. 
Czyli coś w stylu:
```
const worker = action.payload?.worker;
if (worker === undefined) {
   return state
}
{name, employmentTime} = worker;

....
```

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/employee-info.reducer.ts
> +          type: { [action.payload!.worker!.name]: WorkerType.OTHER, ...state.type },
Znowu nie zmieniasz `WorkerType`

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/schedule-data/schedule-data.action-creator.ts
> +  static addNewWorker(worker) {
Brakuje typu argumentu i zwracanego typu.

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/shifts-info.reducer.ts
> +      case ScheduleActionType.MODIFY_WORKER:
Nie uwzględniasz przypadek dodania nowego pracownika.
Przy dodawaniu pracownika, jako `shiftArray` powinna być tworzona nowa lista zawierająca same zmiany wolne.

2021-01-16 02:33 UTC, Qwebeck commented on src/state/reducers/month-state/schedule-data/schedule.actions.ts
> +}
Ten worker nie powinien być  w tym intefejsie: interfejs opisuje cały stan miesiąca, a worker odnosi się tylko do pewnych jego części. 
Mógłbyś powiedzieć po co go używasz?

2021-01-17 12:55 UTC, VVlovsky commented on src/common-models/worker-info.model.ts
> +  time: { [key: string]: string | string[] | number };
![image](https://user-images.githubusercontent.com/36051968/104843572-0da28d80-58d4-11eb-9d55-9b3075c54f32.png)

2021-01-17 14:15 UTC, VVlovsky commented on src/state/reducers/month-state/schedule-data/schedule.actions.ts
> +}
Używam dlatego że action implementuje ten interfejs i w payloadzie posiada pole worker

2021-01-17 17:09 UTC, Qwebeck approved these changes

2021-01-17 17:09 UTC, merged