add "poprawki"
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #173
Opened 2021-01-25 22:53 UTC by kaplonpaulina

2021-01-30 11:08 UTC, kaplonpaulina commented on cypress/integration/e2e/management-tab/edit-worker.spec.js
>          cy.get('[data-cy="employmentTimeOther"] input').should("have.value", "1/2");
zmiana testu, 
zamiast nazwy clasy css jest data-cy

2021-01-30 11:09 UTC, kaplonpaulina commented on src/assets/styles/styles/custom/_errors-loader.scss
>    background: #ffffff;
zmniejsz ikony

2021-01-30 11:10 UTC, kaplonpaulina commented on src/assets/styles/styles/custom/_nametable.scss
> +  }
jak najedziesz na kolumnyh niklikalne nie ma pointera

2021-01-30 11:11 UTC, kaplonpaulina commented on src/components/common-components/dropdown-buttons/dropdown-buttons.component.tsx
> +        <div className="beCenteredDamnit">
napis plu strzałka

2021-01-30 11:12 UTC, kaplonpaulina commented on src/components/schedule-page/edit-page/edit-page-toolbar.component.tsx
> +        </Button>
zmana miejsacami i kolorami

2021-01-30 11:59 UTC, maciekb05 requested changes
Dodałem tam drobne zmiany, ale ogólnie to jest git, faktycznie nie było tego tak dużo 👍

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_dropdown.scss
> +      font-weight: 100;
a nie wystarczy defaultowe 400? czy gdzieś niżej jest zmieniona czcionka?

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_dropdown.scss
>      background-color: white;
jest chyba też zmienna białego koloru

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_dropdown.scss
> +.beCenteredDamnit {
tak jak mówiłaś, trzeba zmienić tę klasę

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_dropdown.scss
> +.beCenteredDamnit {
nazwę*

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_dropdown.scss
>  }
jest jakiś powód dlaczego to #? będzie tylko raz używane na całej applikacji?

2021-01-30 11:59 UTC, maciekb05 commented on src/assets/styles/styles/custom/_nametable.scss
> +  }
wydaje mi się, że to powinna być klasa nie id, może jescze gdzieś tego użyjemy

2021-01-30 11:59 UTC, maciekb05 commented on src/components/common-components/dropdown-buttons/dropdown-buttons.component.tsx
> +          <div className="dropdown-buttons-list" id={dataCy}>
nie wiem, czy chcemy tu używać dataCy (i to jeszcze jako id), raczej to błąd bo już jest raz użyte dataCy w tym komponencie, także też jako data-cy bym nie używał

2021-01-30 11:59 UTC, maciekb05 commented on src/components/namestable/nametable-section.component.tsx
> +
tą funkcję koniecznie trzeba inaczej nazwać, bo jakbym zobaczył isClickable to bym pomyślał, że zwraca boolean.
isClickable to powinna być nazwa argumentu
a funkcja może cursorType, albo coś w tym stylu
dodatkowo tutaj bardzo ładnie można użyć ternary expression ;) ( isClickable ? "pointer" : "default" )

2021-01-30 11:59 UTC, maciekb05 commented on src/components/namestable/nametable-section.component.tsx
>                >
w map nie można używać id, id ma być jedyne na aplikację trzeba użyć klasy i zapewne funkcji classNames, żeby połączyć dwie klasy

2021-02-07 14:09 UTC, pectom commented
@kaplonpaulina czy kotnaktowałaś się z Agą w temacie tego zadania?

2021-02-14 20:32 UTC, merged