[WIP] Task 17
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #184
Opened 2021-02-13 13:58 UTC by Dushess0

![image](https://user-images.githubusercontent.com/44201461/107851639-c1cc0100-6e0b-11eb-9b2b-e96207f1614c.png)

muszę poprawić rozmiar tego modala, żeby nie było widać tego paska po prawej stronie. Bez logiki.

2021-02-19 21:20 UTC, Qwebeck requested changes
Bardzo proszę o zmianę koloru czcionki, ponieważ teraz napisy **Format pliku** oraz **Opcje**
są prawie nieczytelne

![image](https://user-images.githubusercontent.com/21079319/108562567-5ea50780-7300-11eb-9805-444f98b665e0.png)

Też myślę, że można by było pozwolić na ustawienie nazwy przez użytkownika. 
Albo chociażby dodawać datę do nazwy **grafik**

Też chciałbym poprosić o zmianę rozmiaru modala tak, żeby w nim nie pojawiał się scroll

2021-02-19 21:27 UTC, Qwebeck commented
> Bardzo proszę o zmianę koloru czcionki, ponieważ teraz napisy **Format pliku** oraz **Opcje**
> są prawie nieczytelne
> 
> ![image](https://user-images.githubusercontent.com/21079319/108562567-5ea50780-7300-11eb-9805-444f98b665e0.png)
> 
> Też myślę, że można by było pozwolić na ustawienie nazwy przez użytkownika.
> Albo chociażby dodawać datę do nazwy **grafik**
> 
> Też chciałbym poprosić o zmianę rozmiaru modala tak, żeby w nim nie pojawiał się scroll


Dla zmiany rozmiarów powinno zadziałać coś takiego
```ts
/// Robimy to funkcją od width i height
const useStyles = (height: number, width: number) => makeStyles((theme: Theme) =>
  createStyles({
    modal: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    paper: {
      backgroundColor: "#FFFFFF",
      border: "0",
      boxShadow: "-3px 4px 20px 4px rgba(0, 0, 0, 0.15)",
      padding: theme.spacing(2, 1, 3),
     /// Nowy kod
      maxWidth: `${height}px`,
      maxHeight: `${width}px`,
////
      minWidth: "424px",
      minHeight: "198px",
    },
// Trzy kropki dla czytelności
......
)() // Nowy kod. Pojawia się nawias;

export interface ModalOptions {
  setOpen: (open: boolean) => void;
  open: boolean;
  title: string;
  body: JSX.Element;
  footer: JSX.Element;
   // nowy kod
  height: number;
  width: number;
//
}

export default function DefaultModal(options: ModalOptions): JSX.Element {
  /// Wolamy to przekazując odpowiednie parametry
  const classes = useStyles(options.height, options.width);
```

2021-02-20 02:31 UTC, Dushess0 commented
![image](https://user-images.githubusercontent.com/44201461/108580527-20254200-732c-11eb-95c0-ce65c4be554f.png)

2021-02-20 09:34 UTC, Qwebeck requested changes
Dzięki za szybkie poprawki :)
Mam jeszcze prośbę o tym, żeby poprawić dropdown.


![image](https://user-images.githubusercontent.com/21079319/108590953-7fa04380-7366-11eb-903f-7c0c10de0039.png)
On powinien być albo na tym samym poziomie co napisa `Format pliku` (wtedy też potrzeba zmniejszyć rozmiar modala )

Albo być pod tym napisem. ( wtedy można zostawić taki rozmiar )

2021-02-20 09:34 UTC, Qwebeck commented on src/components/common-components/modal/modal.component.tsx
> +        minHeight: "198px",
Btw, to można by było to zrobić tak, żeby można było przekazywać `minWidth` i `minHeigth`. 
Ewentualnie, można też zrobić tak, że to będzie liczone automatycznie na podstawie maxWith/maxHeight.

2021-02-21 15:43 UTC, Dushess0 commented
![image](https://user-images.githubusercontent.com/44201461/108630088-69c47880-7463-11eb-985e-26551a84fbe8.png)
![image](https://user-images.githubusercontent.com/44201461/108630146-a85a3300-7463-11eb-8e48-c57373d1967a.png)
![image](https://user-images.githubusercontent.com/44201461/108630159-b90aa900-7463-11eb-997a-ceb6d2fbb75a.png)
![image](https://user-images.githubusercontent.com/44201461/108630188-da6b9500-7463-11eb-8ee3-7348bd1c2610.png)

2021-02-21 20:33 UTC, Qwebeck approved these changes

2021-02-21 20:33 UTC, merged