Task 319 wiersz z dziennymi pracownikami w grafiku eksportowanym
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #260
Opened 2021-03-06 02:17 UTC by VVlovsky

Zwrócono funkcjonalność exportu wraz z pracownikami dziennymi, parser zmodyfikowano dla obsługi odpowiedniej sytuacji, zaimplementowana obsługa błędów wczytywania.
![image](https://user-images.githubusercontent.com/36051968/110191757-e1ff4680-7e32-11eb-8273-b3d8738c1a46.png)

2021-03-07 08:18 UTC, pectom commented
@kaplonpaulina czekamy na review ;)

2021-03-07 23:26 UTC, kaplonpaulina commented on src/logic/schedule-parser/extra-workers-info.parser.ts
> +  private generateChildren(raw?: string[][]): number[] {
rename

2021-03-07 23:29 UTC, kaplonpaulina commented on src/logic/schedule-parser/children-info.parser.ts
> +      if (raw && raw.length === 3 && raw[2][0].toLowerCase() === "dzieci") {
redundant condition
```suggestion
      if (raw.length === 3 && raw[2][0].toLowerCase() === "dzieci") {
```
check if raw[2] exist before getting first element

2021-03-07 23:31 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
>        if (r && r.length !== 0 && r[0].length !== 0) {
it shouldn' work now?

2021-03-07 23:51 UTC, kaplonpaulina commented on src/logic/schedule-parser/metadata.parser.ts
> +    if (raw.length !== 1 && raw.length !== 3) {
?? do we want 1 row or 3 rows ?? - a bad condition in general

2021-03-07 23:54 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
>      const metadataRaw = rawSchedule.find((r) => r[0][0].toLowerCase().trim() === "dni miesiąca");
you change the rawSchedule, we have to change also this,
metadataRaw was before [["dni miesiąca" , 1 ,2 3,4 ...]]
now:
[["dni miesiąca ...],
["pracownicy dzienni ...],
["dzieci" ...]]

this should be adressed

2021-03-07 23:59 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
> +          if (r.length === 3) {
what if only children are present?

2021-03-08 00:44 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
> +    let dayWorkers;
extraWorkers - let's keep the naming convention

2021-03-08 00:45 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
> +          if (r.length === 3) {
I don't really like this solution, 
I am making MR to your branch with suggestion how I would solve this if we want to have all "dni miesiąca", "pracownicy dzienni", "dzieci" in one array

2021-03-08 00:46 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
> +          if (r.length === 3) {
Please let me know if you agree or think it will make things more complicated

2021-03-08 01:03 UTC, kaplonpaulina requested changes
Please review the suggestion MR and let me know what you think about it, 
I believe changes in the rawShedule should be addressed, it doesn't have to be done as I suggested

2021-03-08 01:07 UTC, kaplonpaulina commented on src/logic/schedule-parser/schedule.parser.ts
> +          if (r.length === 3) {
https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend/pull/268

2021-03-11 16:15 UTC, kaplonpaulina approved these changes

2021-03-11 16:23 UTC, merged