TASK-265-calendar2pdf
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #261
Opened 2021-03-06 05:52 UTC by VVlovsky

![image](https://user-images.githubusercontent.com/36051968/110196948-c60a9d80-7e50-11eb-8d9c-b5f492153acb.png)

![image](https://user-images.githubusercontent.com/36051968/110196927-978cc280-7e50-11eb-9d65-38c2c67a80db.png)

2021-03-07 17:27 UTC, Qwebeck commented on src/assets/styles/styles/custom/_schedule-style.scss
> +  src: url("https://kendo.cdn.telerik.com/2017.2.621/styles/fonts/DejaVu/DejaVuSans-Bold.ttf")
Nie da się w żaden sposób to pobrać i zaimportować?

2021-03-07 17:27 UTC, Qwebeck commented on src/components/namestable/worker-info.component.tsx
> +export class WorkerInfoComponent extends React.Component<WorkerInfoModel> {
Czy mógłbyś przepisać to na komponent funkcyjny?

2021-03-07 17:27 UTC, Qwebeck commented on src/components/namestable/worker-info.component.tsx
> +          fileName="_____.pdf"
Czy mógłbyś uzależnić nazwę pliku od imienia i nazwiska pracownika oraz roku i miesiąca?

2021-03-07 17:27 UTC, Qwebeck commented on src/components/workers-page/workers-calendar/workers-calendar.component.tsx
> +export class WorkersCalendar extends React.Component<CalendarOptions> {
Dlaczego przepisałeś to na komponent klasowy?

2021-03-07 17:29 UTC, Qwebeck requested changes
Co najmniej zmienić nazwę eksportowanego pliku oraz jeśli można zmienić klasowe komponenty na funkcyjne

2021-03-07 18:05 UTC, VVlovsky commented
> Co najmniej zmienić nazwę eksportowanego pliku oraz jeśli można zmienić klasowe komponenty na funkcyjne

Tak, planuję to poprawić kiedy będę pewny co do możliwości wykorzystania tej biblioteki

2021-03-12 02:56 UTC, VVlovsky commented
Możemy zamykać ten branch, znalazłem lepsze rozwiązanie

2021-03-12 06:49 UTC, closed without merging