TASK-323 word count info
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #262
Opened 2021-03-06 08:11 UTC by Ehevi

Informacja o wymaganej liczbie znaków w zgłoszeniu

2021-03-06 08:12 UTC, Ehevi commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
> -    },
spinner był, żeby coś się działo podczas ładowania zrzutu ekranu, teraz nie jest potrzebny

2021-03-06 08:15 UTC, Ehevi commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
> +                  }.`
końcówki fleksyjne 😛
![5](https://user-images.githubusercontent.com/48785655/110200081-5bf7f580-7e5c-11eb-9bbb-3831bebc0e57.png)
![4](https://user-images.githubusercontent.com/48785655/110200083-5f8b7c80-7e5c-11eb-86c1-1d610c1619d9.png)
![1](https://user-images.githubusercontent.com/48785655/110200086-61554000-7e5c-11eb-8e17-204ee82e6e41.png)

2021-03-06 08:16 UTC, Ehevi commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
> -    if (isLongEnough) {
przy za krótkiej wiadomości przycisk "Wyślij" po prostu nie jest aktywny

2021-03-06 13:55 UTC, maciekb05 requested changes
Okej, trochę pewnie przez to, że kilka osób nad tym pracowało zrobił się nieporządek w jednym z plików, ale ogólnie to jest git. Drobne poprawki i można mergować 😃

2021-03-06 13:55 UTC, maciekb05 commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
>    }
Nie mogę przypiąć tego komentarza w odpowiednie miejsce, ale w interfejsie jest jeszcze screenshot, a chyba ma już go nie być

2021-03-06 13:55 UTC, maciekb05 commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
>    }
Wszystkie stałe przesunąłbym na samą górę komponentu, później useEffecty, później funkcje, a na końcu rendery

2021-03-06 13:55 UTC, maciekb05 commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
> +    setIsLongEnough(false);
isLongEnough mogło by być funkcją korzystającą z stanu issueDescription, nie musi być odrębną wartością w State

2021-03-06 13:55 UTC, maciekb05 commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
>                  ? " "
tak samo jak tam wyżej pisałem rzeczy odnośnie renderwoanie na sam dół, żeby zachować kolejność: stałe, useEffecty, funkcje, rendery

2021-03-06 18:35 UTC, maciekb05 submitted a review, later dismissed
body i footer są co prawda stałymi, ale w środku tylko służą do renderowania, je bym dał na sam dół (zaraz przed returnem). Reszta już spoko. Możesz zaraz po tej zmianie mergować. Daję już approve 👍

2021-03-06 19:08 UTC, Ehevi commented
> body i footer są co prawda stałymi, ale w środku tylko służą do renderowania, je bym dał na sam dół (zaraz przed returnem). Reszta już spoko. Możesz zaraz po tej zmianie mergować. Daję już approve 👍

@maciekb05 zrzuciłam body i footer na dół, tak jak pisałeś. Teraz możesz jeszcze raz kliknąć, że Ci się podoba ;)

2021-03-06 19:10 UTC, maciekb05 submitted a review, later dismissed
Super, podoba mi się!

2021-03-06 20:34 UTC, Qwebeck requested changes
Super to zrobiłaś, szczególnie z tymi końcówkami XD

Ale usuń proszę ten `useEffect` bo chyba nie jest potrzebny, a później jak coś nie będzie działać, to może wprowadzić kogoś w błąd

2021-03-06 20:34 UTC, Qwebeck commented on src/components/common-components/modal/report-issue-modal/report-issue-modal.component.tsx
> +    init(`${process.env.EMAIL_KEY}`);
Tutaj powinno być 
```
process.env.REACT_APP_EMAIL_KEY
```

Wiem, że ty tego nie dodawałaś teraz, a po prostu przeniosłaś, ale to jest związane z tym, że my to poprawialiśmy w czasie crunch'a i to nam umknęło.

Ale z racji tego, że wysyłka maili nam działa, to zakładam, że ta metoda nie jest nam potrzebna i można ją usunąć, ponieważ my podajemy `userId` w metodzie `send` 


PS
Zmieniliśmy twoją wcześniejszą nazwę  `EMAIL_KEY`, ponieważ, w przeglądarce nie są widoczne zmienne środowiskowe które nie posiadają prefiksu `REACT_APP_` 

![image](https://user-images.githubusercontent.com/21079319/110219752-4ff24f00-7ec1-11eb-9e6f-fac93e05c19d.png)


https://medium.com/@adostes/using-environment-variables-in-a-react-application-ac3b6c307373

2021-03-07 17:43 UTC, Qwebeck approved these changes
Super !

2021-03-07 17:43 UTC, merged