TASK-333 Asking about unsaved changed when exiting edit mode
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #270
Opened 2021-03-09 09:27 UTC by Ehevi

2021-03-12 17:40 UTC, prenc requested changes
Modal i przycisk zapisywania ok, ale mam wrażenie, że strzałki się nie wyszarzają w ogóle.

Plus czemu w tym zadaniu jest jakiś grafik dodawany?

2021-03-12 21:49 UTC, Qwebeck commented
> Plus czemu w tym zadaniu jest jakiś grafik dodawany?

@prenc 
Dlatego, że puszczaliśmy lokalnie testy, a jeden z testów wygląda tak, że wczytuje grafik, a potem go zapisuje.
I przez to git traktuje go jako nowy

Chyba już jest dodany do `.gitignore`, ale został w historii git'a, przez co on dalej go trakuje. 
Ogarnę to

2021-03-12 22:05 UTC, Qwebeck commented
Teraz git teoretycznie nie powinien trakować ten plik, ponieważ usunąłem go z historii. 

https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2021-03-13 20:41 UTC, prenc approved these changes
Funkcjonalnie nic tutaj się nie zmieniło

2021-03-14 09:51 UTC, Qwebeck approved these changes
Super robota!

2021-03-14 09:51 UTC, merged

2021-03-14 10:04 UTC, Qwebeck commented
> @Qwebeck
> 
> > Super robota!
> 
> ![app](https://user-images.githubusercontent.com/48785655/111064396-1f5b7800-84b4-11eb-8baa-e79f5cba6d1c.png)
 XD
Ale trochę przesadzasz, bo w tym jest też dużo twojej pracy ;)