Task 330 application version
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #273
Opened 2021-03-10 20:48 UTC by maciekb05

Application version:
- add to footer
- add to all requests
- add to pouch db

2021-03-10 20:50 UTC, maciekb05 commented
The semantic-release makes changes to package.json only when added npm extension which is not publishing to npm repository, because the package is public (so it should just update the version in package.json file)
as per: https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository

2021-03-11 10:00 UTC, pectom requested changes
Super, że się już tym zająłeś. Od strony kodu wygląda fajnie. Z rzeczy, które trzeba poprawić to na pewno umiejscowienie zapisu do bazy. Reszta to juz kosmetyka. 
Jeszcze nie zrobiłem testu funkcjonalnego, więc może pojawi się coś jeszcze ode mnie :D

2021-03-11 10:05 UTC, maciekb05 commented on src/api/local-storage-provider.model.ts
> +  private applicationVersionStorage: PouchDB.Database<ApplicationVersionRevision>;
Zobaczyłem, że mamy storage taki z dokumentem typu MonthRevision więc zamiast mieszać i poprawiać cały plik, żeby dostosować do przechowywania czegoś innego poza MonthRevision dodałem nową bazę, nie znam się na PouchDB, mogę poczytać więcej, jak chcemy w jednej wszystko mieć

2021-03-11 10:05 UTC, maciekb05 commented on package.json
> +  "release": {
tak bym przewidywał zgodnie z dokumentacją semantic-release, ale przez te konflikty z masterem nie przetestowałem tego

2021-03-11 10:06 UTC, maciekb05 commented on src/components/common-components/netlify-pro-footer/netlify-pro-footer.component.tsx
> +  useEffect(() => {
okej, ma to sens

2021-03-11 10:06 UTC, maciekb05 commented on src/components/common-components/netlify-pro-footer/netlify-pro-footer.component.tsx
> +      <Grid item>{`Wersja: ${process.env.REACT_APP_VERSION}`}</Grid>
mam taki urywkowy design, tylko wersja w rogu, nie wiem więc co zrobić z Gliderem

2021-03-11 10:34 UTC, pectom commented on src/api/local-storage-provider.model.ts
> +  private applicationVersionStorage: PouchDB.Database<ApplicationVersionRevision>;
W sumie to może tak zostać, bo czasem możemy chcieć wyczyścić bazę z grafikami i nie ruszać tej wersji. Byłem ciekaw czy masz jakieś info na temat jak to działa przy wielu typach dokumentow, ale jak nie sprawdzałeś to ok.

2021-03-11 10:35 UTC, pectom commented on package.json
> +  "release": {
To trzeba sprawdzić przed domergowaniem. Wydaje mi się, że nie musisz nawet do mastera robić merge'a, tylko wystarczy zrobić commit z odpowiednim tagiem

2021-03-11 10:36 UTC, pectom commented on src/components/common-components/netlify-pro-footer/netlify-pro-footer.component.tsx
> +      <Grid item>{`Wersja: ${process.env.REACT_APP_VERSION}`}</Grid>
No z tym designem jest proglem. Mógłbyś się skontaktować z Agą i dopytać?

2021-03-16 06:19 UTC, pectom commented
@maciekb05 i co z tym zadaniem zią? :D

2021-03-20 14:45 UTC, pectom commented on src/app.tsx
> +    new LocalStorageProvider().saveApplicationVersion().then();
Trzeba używać tego then()?

2021-03-20 14:52 UTC, maciekb05 commented on src/app.tsx
> +    new LocalStorageProvider().saveApplicationVersion().then();
żeby ide się nie spinało, że nie kończymy promise, można dać await, ale wtedy useCallback trzeba użyć

2021-03-20 16:37 UTC, pectom commented on src/app.tsx
> +    new LocalStorageProvider().saveApplicationVersion().then();
Oki :)

2021-03-20 16:38 UTC, pectom commented
@maciekb05 i jak tam? Zrobiłeś testy czy to działa?

2021-03-23 22:03 UTC, maciekb05 commented
Na razie changelog ma zapisywać do docs/CHANGELOG.md - później jak będziemy chcieli tego używać to pewnie trzeba będzie do public, albo do src/assets dać czy coś

2021-03-24 07:24 UTC, pectom approved these changes
Good job :D

2021-03-24 07:24 UTC, merged