TASK-256-employees' calendar to pdf
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #277
Opened 2021-03-12 23:51 UTC by VVlovsky

Dodałem możliwośc eksportu, przerobiłem za pomocą opensource bibliotek html2canvas i jspdf. Teraz to działa html->png-pdf.
Zmieniłem tło zmian na biały i dodałem border odpowiedniego koloru żeby był możliwy czarno-biały druk.

![image](https://user-images.githubusercontent.com/36051968/111009973-c7325200-839d-11eb-9946-79558f42eb7e.png)
![image](https://user-images.githubusercontent.com/36051968/111010003-dd401280-839d-11eb-8e3a-78a9307badb3.png)

2021-03-14 11:01 UTC, Qwebeck requested changes
Super praca, ale mam kilka uwag co do kodu. 

Moim zdaniem potrzeba conajmniej wynieść funkcję `exportToPdf` do osobnego pliku. 
Ponadto, było by też dobrze wynieść nazwy klas które są używane w selectorach do stałych albo napisać do tego funkcję. 

To co pisałem o atrybutach - nie jest w sumie ważne. 
Fajnie by było to zrobić, ale żaden problem jeśli tego nie będzie

2021-03-17 12:20 UTC, VVlovsky commented on src/components/namestable/worker-info.component.tsx
> +              "div.BottomCellPart"
@Qwebeck Czyli wszędzie gdzie mamy tą klasę teraz stosować funkcję? Gdzie w takim przypadku ta funkcja ma być?

2021-03-17 12:28 UTC, VVlovsky commented on src/components/namestable/worker-info.component.tsx
> +          if (index === queryLen - 1) {
ale tu chodzi o to że ostatni element w liście ma index długość tej listy - 1

2021-03-17 22:39 UTC, Qwebeck commented on src/components/namestable/worker-info.component.tsx
> +          if (index === queryLen - 1) {
Ok.
Źle zrozumiałem, 
Myślałem, że to wprowadzenie specyficznych styli dla kalendarza

2021-03-17 22:40 UTC, Qwebeck commented on src/components/namestable/worker-info.component.tsx
> +              "div.BottomCellPart"
Tak. 
Np w pliku `base-cell.models`, podobnie jak `baseCellDataCy`
![image](https://user-images.githubusercontent.com/21079319/111547935-30d5a600-877a-11eb-9270-bf301a93c5b6.png)

2021-03-20 16:34 UTC, Qwebeck approved these changes
Teraz jest super :D

2021-03-20 16:35 UTC, merged