Task 350 save changes on next month days
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #283
Opened 2021-03-17 16:03 UTC by pectom

2021-03-17 17:17 UTC, pectom commented
@prenc oprócz zapisywania dni z następnego miesiąca, poprawiłem też kopiowanie pierwszego tygodnia. Teraz już powinno działać normalnie. 

Okazało się, że moje zmiany nie zostały poprawnie domergowane. Przywróciłem to co zrobiłem ostatnio. 
Bląd, nad którym pracował Mateusz by wtedy w ogóle nie wystąpił. Chyba miałem jakieś konflikty i je źle rozwiązałem. PR na 1300 linii to nie był dobry pomysł :)  

Dalej może się pieprzyć jeśli będziemy manipulować pracownikami. ale tym się zajmę w innym tasku. 

Pozdrawiam
TP

2021-03-17 20:15 UTC, prenc reviewed
Wygląda git, ale nie działą mi w ogóle zaznaczanie i edytowanie wielu zmian, ocb?

2021-03-17 20:17 UTC, prenc requested changes
Kasują się zmiany niepracujące w dniach następnego miesiąca przy kopiowaniu.

2021-03-17 20:28 UTC, pectom commented
> Kasują się zmiany niepracujące w dniach następnego miesiąca przy kopiowaniu.
@prenc tak ma być przecież. Jak ktoś ma L4 to nie chcemy, żeby w następnym miesiącu też je miał

2021-03-17 20:29 UTC, pectom commented
> Wygląda git, ale nie działą mi w ogóle zaznaczanie i edytowanie wielu zmian, ocb?

Tutaj nic nie ruszałem z tym. Z tego co widzę, to na developie też się to psuje jakoś losowo.

2021-03-17 20:41 UTC, prenc commented
> > Kasują się zmiany niepracujące w dniach następnego miesiąca przy kopiowaniu.
> > @prenc tak ma być przecież. Jak ktoś ma L4 to nie chcemy, żeby w następnym miesiącu też je miał

Ale ważniejsze jest to, że ustawiam sobie marzec cały, wszystko hula, kopiujemy go na kwiecień i w widoku marca coś się usuwa, tak nie może być.

2021-03-18 15:47 UTC, prenc approved these changes
Działa ode mnie ok, wystawie Janka na code review.

2021-03-18 17:07 UTC, net-runner approved these changes
Dzięki, działa! :)

2021-03-18 17:13 UTC, pectom commented
@prenc to można mergować

2021-03-18 17:50 UTC, merged