Task 361 autocomplete component rendering fix
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #284
Opened 2021-03-17 18:55 UTC by net-runner

Dropdown autocomplete automatycznie pozycjonuje się przy inpucie. Można go zamknąć, zjeżdżając z niego myszką, scrollując bądź klikając gdziekolwiek indziej na stronie.

2021-03-17 20:06 UTC, prenc approved these changes
Dobra robota, ode mnie ok.

2021-03-17 22:30 UTC, pectom requested changes
Request changes ze głównie ze względu na timery. Może ja czegoś nie ogarniam, ale chyba coś tam jest nie tak. Dodatkowo kilka małych uwag. 
Ogólnie to dużo lepiej działa ten dropdown, także szacun :D 

Fajnie, że poprawiłeś też jakieś mniejsze rzeczy. Typu pozbycie się tabeli i syntax sugar z pytajnkami. Ostrzegam jednak, że refactoring jest zakazany (sam dostaję za to nagany XD) Jak działa to raczej nie ruszamy. Chyba, że widzimy jakiegoś nieobsłużonego border case'a albo coś jest na prawdę tragicznie zrobione, ale trzeba to umieć uzasadnić. 

A i plusik za dokumentację :1st_place_medal:

2021-03-17 22:30 UTC, pectom commented on src/components/common-components/autocomplete/autocomplete.component.tsx
> +        clearTimeout(clearModal);
Spoko pomysł z tym timerem, ale trochę się obawiam wycieku pamięci. Zawsze kiedy spotykałem się z timerem to był on w useEffecie, który miał returna czyszczącego ten timer w przypadku odmontowania komponenetu. 

Obecnie może nastąpić taka sytuacja, że timer nie zostanie wyczyszczony, jeśli komponent zostanie odmontowany przed odpaleniem eventu onMouseEnter.

2021-03-17 22:30 UTC, pectom commented on src/components/common-components/folding-section/folding-section.component.tsx
> +      <div style={{ height: opened ? "initial" : "none" }}>{children}</div>
Fajna opcja z tym. Jakoś wcześniej się z tym nie spotkałem, zacznę stosować :D

2021-03-17 22:30 UTC, pectom commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
> +            setIsComponentVisible(false);
Podobnie jak poprzendnio. Coś mi tutaj śmierdzi wyciekiem pamięci. Dodatkowo mamy powtórzenie kodu. Wydaje mi się, że gdybyś to wyniósł do useEffecta to można by to umieścić w osobny pliku i zrobić hooka, którego będziemy sobie mogli reużywać.

2021-03-17 22:33 UTC, Qwebeck requested changes
Tak jak mówił @pectom, to super praca i dropdown teraz jest o wiele lepszy. 

Ale daję request changes z uwagi na to, że znalazłem bug'a :D

2021-03-17 22:33 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
> +    <>
Super pomysł!
 
Jedyne co, to jest problem z `isComponentVisible`:
w funkcji `onMouseLeave`, ty ustawiasz tę flagę na false. W swojej kolei, kiedy ty pokazujesz ekran, to on przesłania komórkę, przez co  jest trigerowana funkcja `onMouseLeave` i ekran znika po 444 sekundach i a z nim również pożądany pozwalający na odkliknięcie

![image](https://user-images.githubusercontent.com/21079319/111546350-d3d8f080-8777-11eb-957c-9e585a844c49.png)


Moja propozycja jest:
ablo usunąć stąd tę flagę, albo zwiększyć z-index na komórce

2021-03-17 22:34 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
> +        />
Źle trafiłem xd
Musiało być tutaj
https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend/pull/284/files#r596423336

2021-03-19 07:37 UTC, pectom commented on src/components/common-components/autocomplete/autocomplete.component.tsx
> +  const pageOffset: number = document.getElementById("root")?.children[0].children[0].scrollTop!;
A co z tym? Bo widzę, że zostawiłeś tak jak było. Boję się, że w runtime, może nam się to wysypać. Dlatego wolałbym wersję z pytajnikami, bez wykrzyknika :D

2021-03-19 07:48 UTC, pectom requested changes
Dokładnie o coś takiego mi chodziło z tym hookiem. SZTOS! 
Request changes, bo komentarz XD Dodatkowo nie odniosłeś się do jednej uwagi, daj znać dlaczego zostawiłeś to w taki sposób (dałem unresolved). 

A i mam pomysł na polepszenie UX. Teraz timer zaczyna odliczanie do zamknięcia po najechaniu na dropdown. Czyli możemy kliknąć komórkę, nie wjeżdzać na dropdown i on będzie cały czas otwarty. Fajnie, gdyby jednak się zamknął po jakimś (dłuższym czasie) nawet jeśli na niego nie najedziemy. 
Jak Ci się spodoba i będziesz chciał to wdrożyć to by było super, ale moim zdaniem można mergować tak jak jest.

2021-03-19 07:48 UTC, pectom commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
> +// import useTimeout from "../base-cell/use-timeout";
Komentarz do usunięcia

2021-03-19 07:50 UTC, pectom commented
@Qwebeck mógłbyś sprawdzić tego buga czy już jest ok?

2021-03-19 09:27 UTC, Qwebeck approved these changes

2021-03-19 09:27 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/base-cell/use-timeout.tsx
> +  //   clear: () => void;
komentarz

2021-03-19 09:28 UTC, Qwebeck commented
> 
> 
> @Qwebeck mógłbyś sprawdzić tego buga czy już jest ok?

Buga już nie ma, więc super. 
Ale przy okazji usunięcia komentarza o którym pisał @pectom , popraw proszę też te moje drobne uwagi

2021-03-19 10:51 UTC, net-runner commented on src/components/schedule-page/table/schedule/schedule-parts/base-cell/use-timeout.tsx
> +  //   clear: () => void;
Już usuwam.

2021-03-19 10:52 UTC, net-runner commented on src/components/schedule-page/table/schedule/schedule-parts/base-cell/use-timeout.tsx
> + * @description useTimeout hook for handling timeouts
Ok

2021-03-19 10:56 UTC, net-runner commented on src/components/common-components/autocomplete/autocomplete.component.tsx
> +  const pageOffset: number = document.getElementById("root")?.children[0].children[0].scrollTop!;
Zapomniałem o tym. Już leci.

2021-03-19 10:59 UTC, net-runner commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-cell.component.tsx
> +// import useTimeout from "../base-cell/use-timeout";
Done

2021-03-19 11:03 UTC, pectom commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-autocomplete.component.tsx
> +        pageOffset !== document.getElementById("root")?.children[0].children[0].scrollTop &&
Jeszcze tu XD

2021-03-19 11:04 UTC, net-runner commented on src/components/schedule-page/table/schedule/schedule-parts/shift-cell/shift-autocomplete.component.tsx
> +        pageOffset !== document.getElementById("root")?.children[0].children[0].scrollTop &&
XDDD

2021-03-19 11:11 UTC, pectom approved these changes
GJ :1st_place_medal:

2021-03-19 11:12 UTC, merged