Task 321 worker groups cherry pick v2
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #293
Opened 2021-03-20 10:40 UTC by Qwebeck

2021-03-20 17:45 UTC, prenc requested changes
Zmiany jak już wiesz

2021-03-20 23:04 UTC, pectom requested changes

2021-03-20 23:04 UTC, pectom commented on src/components/schedule-page/table/schedule/sections/foundation-info-section/foundation-info.component.tsx
> +      // TODO: Fix unkonw
:)

2021-03-20 23:04 UTC, pectom commented on src/state/reducers/worker.action-creator.ts
> +  static replaceWorkerShiftsInTmpSchedule(newWorkerShifts: ShiftInfoModel): ThunkFunction<unknown> {
Może osobny action creator

2021-03-21 08:05 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/sections/worker-info-section/worker-info-section.component.tsx
> +  data: WorkerInfo[];
W którymś z interfejsów wyżej to juz jest, więc proponuję nie wprowadzać dodatkowych zmian teraz
![image](https://user-images.githubusercontent.com/21079319/111898156-91880b80-8a24-11eb-8a52-94ee7cb416cb.png)

2021-03-21 08:06 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/base-cell/cell-details-content.component.tsx
> +      <div>{workerName}</div>
Nie wiem, co można dać jako wartość domyślną dla imienia, więc na razie zrobiłem tak, ze ten blok pojawia się warunkowo

2021-03-21 18:05 UTC, pectom approved these changes
Świetna praca @Qwebeck!!!

2021-03-21 18:35 UTC, merged