TASK-390 Footer odlepiony od dołu ekranu
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #294
Opened 2021-03-20 15:06 UTC by maciekb05

2021-03-20 16:36 UTC, pectom submitted a review, later dismissed

2021-03-20 16:36 UTC, pectom commented
@maciekb05 dałem approve'a, ale akurat konflikty wywaliło

2021-03-20 17:44 UTC, prenc requested changes
Nie zawsze przylepia się do samego dołu
![image](https://user-images.githubusercontent.com/26227269/111880486-3a465480-89ac-11eb-99fa-a5a5be088244.png)

2021-03-21 15:58 UTC, prenc approved these changes
Wydaje się teraz być ok.

2021-03-21 15:58 UTC, merged