TASK-411 Export with worker groups
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #299
Opened 2021-03-22 16:07 UTC by pectom

2021-03-22 16:11 UTC, pectom commented
@prenc dodałem eksport grup pracowników. Jako, że mieszałem w eksporcie, który nie działa w moim innym [PR](https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend/pull/296)  to zrobiłem sobie o niego reabase'a i to też poprawiłem.

W praktyce tutaj domergujemy 2 zadania.
TASK-411 i TASK-396
Nie usuwałem PR z TASK-396 tylko zamieniłem go na drafta, żeby reviewer mógł sobie zerknąć na mniej kodu tam.

2021-03-22 17:58 UTC, prenc requested changes
Z jakiegoś powodu pierwszy row exporta ma inne formatowanie niż reszta (i kolory nie działają)
![image](https://user-images.githubusercontent.com/26227269/112035966-62ff5300-8b40-11eb-9a5c-a5bb02aaa78b.png)

2021-03-22 17:59 UTC, prenc requested changes
A i jeszcze jedna rzeczy, bo Agata nas zabije.
![image](https://user-images.githubusercontent.com/26227269/112036250-b376b080-8b40-11eb-9c08-22c05c671bcd.png)

2021-03-23 11:00 UTC, Qwebeck approved these changes
Jest super, można mergować. 
Bardzo ładnie wygląda po tym refaktoringu

2021-03-23 11:04 UTC, pectom commented on src/logic/schedule-exporter/schedule-info-export.logic.ts
> +    const shiftSectionStartIndex = 1 + foundationInfoLen + HEADER_LEN + emptySpace; // +2 because of header
usunięte

2021-03-23 11:20 UTC, merged