TASK-419 styling for non working shifts
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #316
Opened 2021-03-24 17:28 UTC by net-runner

Od teraz zmiany nie pracujące są stylowane dynamicznie

2021-03-24 17:38 UTC, prenc requested changes
Chyba wszystkie kody w komórkach są przesunięte trochę w lewo

2021-03-24 18:46 UTC, pectom requested changes
Na razie funkcjonalnie jeszcze trzeba to poprawić:
1. Złe tło w nagłówku
![image](https://user-images.githubusercontent.com/23723122/112366664-5eba6d80-8cd9-11eb-9265-9c2528337bfc.png)
2. Zmiany OP/NZ nie są ciągłe 
![image](https://user-images.githubusercontent.com/23723122/112366691-68dc6c00-8cd9-11eb-83c4-442a264be82e.png)

2021-03-24 20:31 UTC, pectom approved these changes
Jest w porzo :D

2021-03-25 13:59 UTC, prenc requested changes
Kompletnie nie widać tego O8
![image](https://user-images.githubusercontent.com/26227269/112484963-b5c44f00-8d7a-11eb-8848-f067fa20e740.png)
O12 ucina
![image](https://user-images.githubusercontent.com/26227269/112485079-d2f91d80-8d7a-11eb-9507-365ea779e7a5.png)

@pectom czemu mamy te O12 itd a nie ma OK (czy k12, 8)?

2021-03-25 14:10 UTC, pectom commented
Nie mieściły się w kratce i bardzo brzydko to wyglądało. To było najszybsze rozwiązanie jakie przyszło mi do głowy xD

2021-03-26 12:37 UTC, Qwebeck approved these changes
Super jest :D

2021-03-26 12:38 UTC, merged