TASK-400 task set-up
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #320
Opened 2021-03-24 22:20 UTC by Dimonium-239

2021-03-31 19:22 UTC, prenc requested changes
Modal spoko, ale są konflikty.

Dodatkowo opcja eksportu do zipa w ogole nie działa, a z tego co rozumiem jest w scopie tego zadania.

2021-04-01 17:05 UTC, Dimonium-239 commented
Opcja eksportu do zipa nie działała ponieważ w którymś z grafiku pole dotyczące umowy o prace miał wartość `undefined`. W funkcji `setWorkersWorkSheet` podmieniam każdą wartość `undefined` na 0. Mogę kontynuować to zadanie i szukać dlaczego tam się pojawia `undefined` ponieważ nie oczekujemy go tam, czy mogę przejść do bardziej aktualnych zadań?

2021-04-01 20:13 UTC, prenc requested changes
Wydaje mi się, że UXowo powinno być tak, że jak ten modal zostanie rozwinięty nie powinien być móc ponownie zwinięty, a tekst powinien być wyszarzony.

2021-04-01 21:58 UTC, prenc requested changes
1. Grafiki są eksportowane bez informacji o nadgodzinach
2. Po eksporcie całej historii aplikacji powinna się odświeżać

2021-04-16 19:27 UTC, Qwebeck approved these changes
Na razie ok.
Poźniej wystawimy zadanie na uwagi od @prenc

2021-04-16 19:28 UTC, merged