TASK-444 finished tests refactoring.
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #358
Opened 2021-04-16 23:51 UTC by kopcion

2021-04-17 09:25 UTC, kopcion commented on cypress/integration/unit/helpers/worker-hours-info.spec.ts
> +//todo refactor
a no tak, jeszcze ten plik :)

2021-04-17 09:35 UTC, Qwebeck commented on cypress/integration/unit/helpers/worker-hours-info.spec.ts
> +//todo refactor
Masz stare pliki
Teraz ten test trochę inaczej wygląda
Zobacz jak jest na developie albo next'ie

2021-04-17 09:37 UTC, kopcion commented on cypress/integration/unit/helpers/worker-hours-info.spec.ts
> +//todo refactor
bede robic rebase i tak, zerkne po rebase na wszystkie testy jeszcze raz

2021-04-17 09:42 UTC, Qwebeck commented on cypress/integration/unit/helpers/worker-hours-info.spec.ts
> +//todo refactor
Tylko ten się zmienił
Tam doszły nowe testy bo trochę zmieniła się logika liczenia nadgodzin

2021-04-18 07:59 UTC, pectom requested changes
Czekamy na rozwiązanie konfliktów :)

2021-04-20 17:47 UTC, kopcion commented
New PR from origin/next

2021-04-20 17:47 UTC, closed without merging