TASK-442 Introduce WTC errors
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #359
Opened 2021-04-17 10:39 UTC by pectom

2021-04-20 07:40 UTC, Ehevi commented on src/components/error-list/error-list-item.component.tsx
> +  }
bez tego fragmentu znajduje np. substring `Opiekunka 1` w stringu `Opiekunka 10` (jeżeli jest wcześniej w komunikacie błędu)

2021-04-20 09:35 UTC, Ehevi commented on src/helpers/error-message.helper.ts
> +        message += `<br>Niedozwolone połączenie zespołów: <b>${error.workers.join(", ")}</b>.`;
Ogólnie komunikat tego błędu mi się nie podoba, bo zdecydowanie za mało mówi (wg mnie dla każdego przypadku powinno info kto z kim z jakiego zespołu, na jakiej zmianie i kiedy: godziny), ale jeżeli chcemy agregować godziny po dniach, to dla wersji "rozszerzonej" treść pojedynczego błędu byłaby bardzo dłuuuga, więc chyba musi zostać tak jak teraz ¯\\\_(ツ)\_/¯

2021-04-23 12:27 UTC, Qwebeck requested changes
Według mnie wszystko jest super, ale mam jeszcze prośbę o uejdnolicenie nazw `workerGroup` i `team`

2021-04-23 12:27 UTC, Qwebeck commented on src/logic/schedule-providers/schedule-provider.model.ts
> +      shifts: sections.WorkerGroups.map((section) => section.workerShifts).reduce(
Zmieniałaś nazwę `workerGroups` na `teams`, ale w niektórych miejscach dalej jest workerGroups.
Proponuję to ujednolicić.
Łatwiej chyba będzie przywrócić `workerGroups`

2021-04-23 16:07 UTC, Ehevi commented on src/logic/schedule-providers/schedule-provider.model.ts
> +      shifts: sections.WorkerGroups.map((section) => section.workerShifts).reduce(
A nie było przypadkiem tak, że miałam zmienić `teams` z powrotem na `workerGroups`? XD

2021-04-23 16:38 UTC, Ehevi commented on src/logic/schedule-providers/schedule-provider.model.ts
> +      shifts: sections.WorkerGroups.map((section) => section.workerShifts).reduce(
Tyle że z backendu przychodzą jako `teams` i muszą się zgadzać żeby to działało
https://github.com/Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-solver#workers-teams

2021-04-23 16:51 UTC, Ehevi commented on src/logic/schedule-providers/schedule-provider.model.ts
> +      shifts: sections.WorkerGroups.map((section) => section.workerShifts).reduce(
@Qwebeck czyli mogę albo to zostawić tak jak jest teraz, albo podmienić wszystkie `workerGroup` na `team`

2021-04-25 22:00 UTC, Qwebeck commented on src/logic/schedule-providers/schedule-provider.model.ts
> +      shifts: sections.WorkerGroups.map((section) => section.workerShifts).reduce(
Tak jak rozmawialiśmy na planingu.
Najważniejsze jest ujednolicenie tego. 
Można zrobić tak jak twoim zdaniem jest najlepiej

2021-04-26 16:52 UTC, Qwebeck requested changes
Ja bym zmienił też tę nazwę na coś w stylu WorkersByTeam

![image](https://user-images.githubusercontent.com/21079319/116120600-fdaefc80-a6bf-11eb-9bb8-f6ad5cf39513.png)

Espero con ansias la cuarta parte :)

2021-04-26 19:22 UTC, Qwebeck approved these changes
Increíblemente!

2021-04-26 19:22 UTC, merged