TASK-450 Algorithm errors found info
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #361
Opened 2021-04-19 20:19 UTC by Sig00rd

2021-04-24 13:14 UTC, net-runner commented on src/pages/schedule-page/read-only-tab/read-only-toolbar.tsx
> +  const [areAlgoErrorsPresent, setAreAlgoErrorsPresent] = React.useState<boolean>(false);
useState nie musisz typować jeśli korzystasz z prostych typów, jest to robione automatycznie.

2021-04-24 13:19 UTC, net-runner requested changes
Małe zmiany i będzie git.

2021-04-24 13:19 UTC, net-runner commented on src/pages/schedule-page/read-only-tab/read-only-toolbar.tsx
> +              <p>Plan zawiera błędy. Zobacz je w trybie edycji</p>
Jest Git. Tylko tutaj jakbyś wykorzystał funkcje t z ./translations.helper.tsx i dodał odpowiednie klucze do plików en.tsx i pl.tsx, ponieważ teraz korzystamy z lokalizacji i zbieramy stringi w jedno miejsce.

2021-04-26 16:44 UTC, Sig00rd commented on src/pages/schedule-page/read-only-tab/read-only-toolbar.tsx
> +              <p>Plan zawiera błędy. Zobacz je w trybie edycji</p>
Dzięki, poprawione

2021-04-27 19:42 UTC, net-runner approved these changes
Gra :)

2021-04-27 19:42 UTC, merged