TASK-449 Export of monthly leaves
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #369
Opened 2021-05-04 10:14 UTC by Ehevi

2021-05-11 09:26 UTC, Ehevi commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +            ),
Tak zrozumiałam to, co jest [tutaj](https://firebasestorage.googleapis.com/v0/b/tara-cloud.appspot.com/o/orgs%2Fnurse-scheduling%2Ftasks%2F449%2Fimage-7511d6f1-7b7c-4134-a698-4030792b0cee.png?alt=media&token=8fc7466e-2470-4229-80c6-b6913791a276) i pierwszy z brzegu internetowy artykuł, ale nie jestem pewna, czy dobrze liczę godziny urlopu. Jak ktoś wie, niech mnie poprawi.

2021-05-11 20:12 UTC, pectom commented
Nie eksportować informacji o niezatrudnionych zmianach pracownika. 
Usunięcie danych o roku (ma być pusta kolumna) i zmiana nagłówka na "za rok".

2021-05-13 14:01 UTC, Ehevi commented
- [x] dni urlopu liczone bez świąt i weekendów
- [x] Nagłówek `Rok` -> __`Za rok`__ + ta kolumna powinna być pusta
- [x] pominięcie niezatrudnionych pracowników
- [x] wolne godziny liczone `WorkerHourInfo.calculateFreeHoursForContractType` (dla danego pracownika na cały miesiąc)

2021-05-14 06:23 UTC, pectom requested changes
Eksport jest supcio :D Niestety dalej są problemy z algorytmem:
1. Nie wiemy jak liczyć ile godzin (możliwe, że mamy to w kodzie, ale to nie jest ta funkcja, którą Ci wskazaliśmy)
2. W przykładowym eksporcie nie ma infomacji o ilości godzin dla urlopów zdrowotnych. Nie mam pojęcia dlaczego 🙅 

Jednak nie chcę żebyś się tym zajmowała w ramach tego zadania. My musimy zrobić reasearch na ten temat, jak już dowiemy się co i jak to wtedy to wystawimy zadanie na poprawę tego. 

W kwestii poprawek do tego zadania to:
- [ ] mergowanie może zostać tylko dla "Imię i nazwisko". 
- [ ] Translacje
- [ ] Małe poprawki lub uzasadnienie nazewnictwa
- [ ] Wyniesienie warunku do stałej 
- [ ] Rozbicie metody setWorkersWorkSheet na mniejsze funkcje

2021-05-14 06:23 UTC, pet1wz commented on src/helpers/parser.helper.ts
> +export const LEAVES_WORKSHEET_NAME = "urlopy";
Teraz wszystkie napisy wrzucamy do src/assets/translations do pl.ts i en.ts

2021-05-14 06:23 UTC, pet1wz commented on src/helpers/parser.helper.ts
> +export const ABSENCE_HEADERS = [NAME_SURNAME, "Typ", FROM, TO, "Ile dni", "Ile godzin", "Za rok"];
Tutaj podobnie -  pasuje przenieść to do translacji

2021-05-14 06:23 UTC, pet1wz commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +  public setWorkersWorkSheet(workSheet: xlsx.Worksheet): void {
Coś nie tak z nazwą funkcji chyba - raczej powinno być coś ala -> setAbsenceSheet

2021-05-14 06:23 UTC, pet1wz commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +  private cellsToMerge: number[][];
A dlaczego to jest zmienna klasy? Może skoro nie przekazujemy tego w konstruktorze, to niech będzie to zmienna tworzona w publicznej funkcji, przekazywana do prywatnej

2021-05-14 06:23 UTC, pet1wz commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +  private createWorkersInfoSection(
To samo tutaj jeśli chodzi o nazwę. Mi workers info section bardziej kojarzy się z innym arkuszem - tym, który ma typowo informacje o pracowniku. Dlatego wolałbym, żeby to zmienić, bo może nam się w przyszłosci mylić trochę :D

2021-05-14 06:23 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +              WorkerHourInfo.calculateFreeHoursForContractType(
Z tego co widzę to niestety nie działa np. Pracownik ma urlop w normalne dni, ale pomimo tego ma dalej 0 nadgodzin. Musimy jeszcze to przemyśleć i napisać algorytm do liczenia tego, ale nie będzie to już częścią tego zadania.

2021-05-14 06:23 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +                verboseDates[index].isPublicHoliday ||
Dwa razy ten sam warunek. Może by wynieść go do stałej. Mniej kodu + nazwa będzie opisywać co oznacza.

2021-05-14 06:23 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +    this.cellsToMerge.forEach((pair, index) => {
Podoba mi się mergowanie dla kolumny pracownika, ale niestety nie może mergować godzin i roku. 
Widzę tutaj 2 problemy: 
1. Urlop może być za inny rok w każdym przypadku 
2. Z tego co widzę to nie liczą godzin dla zwolenień lekarskich, izolacji itd. To raczej też nie jest liczone za jakiś rok. Nie wiem z czego to wynika do końca. Musimy się dowiedzieć.

2021-05-14 06:23 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +      workerShifts.forEach((shift, index) => {
Dość długa i nieczytelna funkcja wyszła. Może by rozbić jakoś tę logikę na nowe funkcje. Łatwiej się będzie połapać o co chodzi. Z tego co przychodzi mi do głowy to do funkcji wynieść  np. 2 ścieżki z ifa, to co mamy w while'u

2021-05-14 10:56 UTC, Ehevi commented
Poprawiłam (z dokładnością do tego, że liczenie godzin nie działa 😛).
> ale niestety nie może mergować godzin i roku

funkcja `calculateFreeHoursForContractType` właśnie liczy wolne godziny dla całego miesiąca (dlatego też był merge), a nie dla "konkretnego typu", ale jak na razie i tak nie działa jak trzeba, więc zostawiłam jak jest. Chyba, że czytelniejszą wersją _tego jeszcze nie ma_ jest wpisanie wszędzie w miejsce godzin `0` / zostawienie pustej kolumny.

2021-05-14 15:04 UTC, pectom requested changes
Wszystko ładnie wprowadzone, ale naszło mnie jeszcze na kolejne poprawki (nie bądź zła XD) Dążymy do perfekcji 🥇

2021-05-14 15:04 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +            this.pushWorkersRow(
Zawsze wywołujemy tę funkcję tylko `name` jest inny. Zamieniłbym to na ustawianie name'a w if/else i wywołanie funkcji na końcu, będzie czytelniej :D

2021-05-14 15:04 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +        if (shift !== ShiftCode.W && shift !== ShiftCode.NZ && !SHIFTS[shift].isWorkingShift) {
Może ten warunek też do stałej np. `isNotExcludedShift`?

2021-05-14 15:04 UTC, pectom commented on src/logic/schedule-exporter/workers-absence-export.logic.ts
> +    cellsToMerge.forEach((pair, index) => {
Co prawda wcześniej o tym nie wspomniałem, ale ładnie to wyszło w tej drugiej funkcji, więc może i tę udałoby się tak podzielić na prywatne funkcje. Dużo łatwiej się to czyta.

2021-05-15 08:45 UTC, pectom approved these changes
Pięknie <3

2021-05-15 08:46 UTC, merged