Task 461 base cell refactor
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #374
Opened 2021-05-09 23:29 UTC by Qwebeck

2021-05-09 23:36 UTC, Qwebeck reviewed
Głownie poprzenosiłem kod do osobnych plików.

2021-05-09 23:36 UTC, Qwebeck commented on src/components/common-components/mouse-event-listener/mouse-event-listener.tsx
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Logika do nasłuchiwania na kliknięcie myszą oraz scrolowanie którą wcześniej robił Janek. 
Wyniosłem do osobnego plik, bo może się przydać

2021-05-09 23:36 UTC, Qwebeck commented on src/components/schedule/worker-info-section/shifts-section/shift-cell/shift-cell-content.component.tsx
> +/* This Source Code Form is subject to the terms of the Mozilla Public
To co my widzimy w komórce kiedy nie jest otwarty dropdown ze zmianami

2021-05-09 23:36 UTC, Qwebeck commented on src/components/schedule/worker-info-section/shifts-section/shift-cell/shift-cell.component.tsx
> +/* This Source Code Form is subject to the terms of the Mozilla Public
Główny plik który refaktorowałem

2021-05-09 23:36 UTC, Qwebeck commented on src/helpers/colors/color.helper.ts
> +  public static hexToRgb(hex: string): Color {
Użyłem API które już było

2021-05-10 19:09 UTC, pectom requested changes

2021-05-10 19:09 UTC, pectom commented on src/components/common-components/mouse-event-listener/mouse-event-listener.tsx
> +    <div
Do style components

2021-05-10 19:09 UTC, pectom commented on src/components/schedule/worker-info-section/shifts-section/shift-cell/shift-cell.component.tsx
> +// Create a config file, that will contain this definitions
Brakuje TODO

2021-05-11 10:30 UTC, merged