TASK-473 styles migration to styled components
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #378
Opened 2021-05-12 22:50 UTC by T0mec

2021-06-07 13:05 UTC, Qwebeck requested changes
Szczerze mówiąc, dość trudno wyłapać jakieś problemy.
Dodałem komentarze w kilku miejscach i też znalazłem jeden problem na pdoglądzie: 
wielkości czcionek zlekka się rozjechały.
 Głównie przez niego `Request Changes`

![image](https://user-images.githubusercontent.com/21079319/121021093-4cf94a00-c7a1-11eb-898f-5ea94740676d.png)

2021-06-07 13:05 UTC, Qwebeck commented on src/app.styled.ts
> +  box-shadow: 0px 0px 5px 0px #00000015;
Co do koloru, to według mnie lepiej by było użyć w tym miejscu stalej którą mamy zdefiniowaną w kolorach.
![image](https://user-images.githubusercontent.com/21079319/121015811-b2e2d300-c79b-11eb-9bf9-f633ddd13958.png)

Czyli było by coś w stylu:
`box-shadow: 0px 0px 5px 0px ${fade(colors.black)}`
gdzie `fade` - to funkcja z `Material-UI`.
![image](https://user-images.githubusercontent.com/21079319/121016060-fb9a8c00-c79b-11eb-89fd-fb62ff467831.png)

2021-06-07 13:05 UTC, Qwebeck commented on src/assets/colors.ts
> +export const fontSizeH6 = `${0.75}rem`;
1. Proponuję zmienić nazwę tego pliku na coś w stylu `css-consts.ts`, ponieważ teraz nazywa się `colors` mimo tego, że tutaj są nie tylko kolory.
2. Proponuję zostawić uzaleźnienie od `font-size-base`, ponieważ wtedy będziemy mieli wygodnijeszą kontrolę nad wielkością nagłowków.
![image](https://user-images.githubusercontent.com/21079319/121016885-f7bb3980-c79c-11eb-8fbf-0858f19b7c7e.png)

2021-06-07 13:05 UTC, Qwebeck commented on src/assets/colors.ts
> +export const fontSizeH6 = `${0.75}rem`;
I też pytanie, czy my faktycznie używamy tych stałych?
Bo ja nie widzę gdzie.

2021-06-07 20:54 UTC, T0mec commented on src/app.styled.ts
> +  box-shadow: 0px 0px 5px 0px #00000015;
Zrobione.

2021-06-07 20:54 UTC, T0mec commented on src/assets/colors.ts
> +export const fontSizeH6 = `${0.75}rem`;
`fontSizeH4` było użyte w  headerze drawera, ale jak to wyżej zauważyłeś, wielkości czcionek się trochę rozjeżdżały. Zamieniłem to w headerze na `fontSizeLg`, a wszystkie te nieużywane rozmiary usunąłem, więc jest już git.

2021-06-11 17:15 UTC, Qwebeck commented on src/assets/colors.ts
> +export const fontSizeH6 = `${0.75}rem`;
Super!

2021-06-11 17:27 UTC, Qwebeck approved these changes
Super robota!

2021-06-11 17:55 UTC, merged