NS-92
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #45
Opened 2020-10-26 10:10 UTC by maciekb05

2020-10-28 14:11 UTC, Qwebeck requested changes
Myślę, że to musiało by pojawić się w logach

https://www.youtube.com/watch?v=0n5_PJJAEUI&feature=youtu.be

Żeby powtórzyć bug należy zmienić w add-worker-modal funkcję `parseTimeIfPossible` na :
```javascript
 function parseTimeIfPossible(time: string): ParseTimeModel {
    /* error source */
     const errorSouce: any = null;
     const b = errorSouce.home;

    if (new RegExp("([0].[0-9])|(1.0)|(1)").test(time)) {
      return { isTimeFormatValid: true, parsedTime: Number(time) };
    }
    if (new RegExp("[1-9]/[0-9]").test(time)) {
      const timerArray = time.split("/").map(parseInt);
      if (timerArray[0] <= timerArray[1]) {
        return { isTimeFormatValid: true, parsedTime: Number(timerArray[0] / timerArray[1]) };
      }
    }
    return { isTimeFormatValid: false };
  }
```

2020-10-31 18:47 UTC, maciekb05 commented
Czekamy na @pectom, żeby potwierdził czy na aplikacji zdeployowanej na Netlify będzie działało Sentry

2020-11-02 17:55 UTC, pectom commented
Zrobiłem deploy tego brancha na Netlify https://nurse-scheduling.netlify.app/, ale nie mam danych do logowania do Sentry, żeby móc to sprawdzić.

2020-11-02 20:32 UTC, pectom approved these changes

2020-11-02 20:32 UTC, merged