NS-76
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #53
Opened 2020-10-30 13:53 UTC by kaplonpaulina

ogólnie w styles/custom tworzymy _component-name.scss dla każdego componentu
w styles-all.scss załączamy kolejne pliki, w samym projekcie wystarczy raz zimportować plik scss w index.tsx

wszystkie zmienne do _variables.scss (w tym momencie mam przykłady z innego projektu)

zostawiłam mixins i bootstrap żebyście się zapoznali z róznymi możliwoścami, np. _buttons.scss może być pomocny w zastąpieniu helpers/colors -> Według mnie to powinno być przenieisone jako styl, co o tym sądzicie?

Po usłyszeniu komentarzy z waszej strony, posprzątam wszystkie niepotrzebne rzeczy na tą chwilę.
Myślę jednak, że mogą się przydać po poznaniu projektu.

PS. udało mi się pozbyć suwaka pod tabelką ^^

2020-11-01 01:31 UTC, Qwebeck commented
![image](https://user-images.githubusercontent.com/21079319/97793273-388d1780-1bea-11eb-8311-624c228cb5a5.png)

Rzeczywiście się udało i o wiele lepiej to wygląda :)

2020-11-01 01:33 UTC, Qwebeck commented on frontend/src/assets/styles/styles/bootstrap/mixins/_image.scss
> +  }
Brakuje klamry. To musi wyglądać tak: 
```
  @media only screen and (min-resolution: 192dpi) {
    // IE9-11 don't support dppx only screen and (min-resolution: 2dppx) {
    // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }

2020-11-01 01:34 UTC, Qwebeck commented
![image](https://user-images.githubusercontent.com/21079319/97793319-bea95e00-1bea-11eb-8b87-f627587255ef.png)

Został jeszcze jeden `css`

2020-11-03 22:17 UTC, Qwebeck requested changes
Zupdatować _image.scss ( lub usunąć ), przenieść `shift-row.css` na ten górny poziom. I jeżeli się nie mylę, to ty mówilaś, że zamierzasz usunąć te przykladowe pliki, scss kiedy my je zobaczymy. @pectom ?

2020-11-04 21:53 UTC, pectom commented
Zapoznałem się z przykładami, więc jak dla mnie można je usuwać :)

2020-11-04 21:56 UTC, pectom requested changes
Fajne to je:+1: Zapoznałem się z przykładami, więc jak dla mnie można je usuwać. Jeśli chodzi o zmiany to nihil novi, tylko to o czym wspomniał @Qwebeck A i jeśli chodzi o te kolorki to spoko, żeby to było konfigurowane w stylach, a nie w kodzie. Można dodać task na zmianę tego.

2020-11-04 22:01 UTC, Qwebeck commented
> 
> 
> Fajne to je👍 Zapoznałem się z przykładami, więc jak dla mnie można je usuwać. Jeśli chodzi o zmiany to nihil novi, tylko to o czym wspomniał @Qwebeck A i jeśli chodzi o te kolorki to spoko, żeby to było konfigurowane w stylach, a nie w kodzie. Można dodać task na zmianę tego.

To, że kolorki są konfigurowane w kodzie jest związane z tym, że chcemy mieć takie same kolorki dla excela i nie wiem, czy dało by się użyć style od css przy eksportowaniu plików

2020-11-06 14:16 UTC, Qwebeck approved these changes
Dla mnie wygląda dobrze, ale niestety nie dam rady przed spotkaniem tego uruchomić i zobaczyć jak to wygląda.

2020-11-06 14:17 UTC, Qwebeck commented on frontend/src/components/toolbar/problem-metadata/problem-metadata.component.tsx
> +      <div id="submit-button-container">
Bardzo słuszna zmiana !

2020-11-06 14:17 UTC, Qwebeck commented on frontend/src/components/toolbar/toolbar.component.tsx
> +    <div className="toolbar-container">
O wiele lepsza nazwa niż `header` ;)

2020-11-06 16:12 UTC, pectom approved these changes

2020-11-06 18:24 UTC, merged