TASK-6
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #61
Opened 2020-11-09 19:09 UTC by maciekb05

2020-11-09 20:35 UTC, Sig00rd approved these changes

2020-11-09 21:42 UTC, pectom requested changes
Słaby jest trochę opis zadania. W teście chodziło o to, żeby sprawdzić czy utworzył się poprawny stan aplikacji w Reduxie. Jego wyświetlanie ma być sprawdzone w osobnym zadaniu.

2020-11-11 18:40 UTC, pectom commented
Mógłbyś zmienić nazwę taska i opisy na Tarze to wtedy dam approve'a :D

2020-11-12 12:35 UTC, pectom approved these changes

2020-11-12 12:36 UTC, merged