TASK-11
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #62
Opened 2020-11-09 21:24 UTC by maciekb05

Dodaję też @prenc jako eksperta od systemów operacyjnych i komendy whoami, której użyłem

2020-11-09 22:06 UTC, pectom requested changes
Akurat ja mam nazwy folderów po polsku i u mnie ten test nie przechodzi :( Przydałoby się w jakiś inny sposób określać gdzie znajduje się pobrany grafik :/ 
![Screenshot from 2020-11-09 23-01-19](https://user-images.githubusercontent.com/23723122/98602098-39a40000-22e0-11eb-9168-bfea94283eeb.png)

2020-11-10 11:28 UTC, prenc commented
Nie no, puściłem i failuje, zdziwiłbym się jakby działało. Używasz jakiś pełnych ścieżek (co zawsze jest złą praktyką), jak każdy ma inny system operacyjny, to nie ma szans działać. A na Windowsie, to ja nie wiem czy Ci w ogóle whoami zadziała. 

![image](https://user-images.githubusercontent.com/26227269/98668264-ed90a400-234f-11eb-83a9-ead6b05df343.png)

2020-11-10 11:53 UTC, maciekb05 commented
> Nie no, puściłem i failuje, zdziwiłbym się jakby działało. Używasz jakiś pełnych ścieżek (co zawsze jest złą praktyką), jak każdy ma inny system operacyjny, to nie ma szans działać. A na Windowsie, to ja nie wiem czy Ci w ogóle whoami zadziała.
> 
> ![image](https://user-images.githubusercontent.com/26227269/98668264-ed90a400-234f-11eb-83a9-ead6b05df343.png)
> Na pewno jest jakaś biblioteka, która robi unikalny temp folder i tam możesz zapisywać ten grafik.

No wiem, że to nie jest najlepsze wyjście, pytanie czy da się wymusić zapisywanie w tym temp folderze. @Qwebeck co o tym sądzisz, trzeba by przerabiać front, żeby dało się z testów wymusić zapisywanie w jakimś danym folderze?

2020-11-10 19:00 UTC, Qwebeck commented on cypress/integration/header-control-menu/menu-plik.spec.js
> +        cy.readFile(`/Users/${user}/Downloads/grafik.xlsx`).then((file) =>{
To jest mega duże niedopatrzenie z mojej strony, że nie da się wybrać ścieżki.
Muszę to poprawić, i spróbuję to zrobić na podstawowym poziomie ( przekazujesz folder do którego chcesz zapisać harmonogram) już w tym tygodniu

2020-11-10 19:00 UTC, Qwebeck commented on cypress/integration/header-control-menu/menu-plik.spec.js
> +        cy.readFile(`/Users/${user}/Downloads/grafik.xlsx`).then((file) =>{
Poprawię wtedy też ten test

2020-11-11 16:58 UTC, prenc approved these changes

2020-11-11 21:11 UTC, Qwebeck commented
https://github.com/eligrey/FileSaver.js/issues/297
To zadanie okazało się być nieco trudniejszym niż oczekiwałem. Będę musiał to w jakiś sposób przekminić, ale nie wiem czy dam radę do piątku

2020-11-12 12:47 UTC, maciekb05 commented
No faktycznie, nawet w CI ta ścieżka jest zła, więc trzeba coś rozkminić lepiej

2020-11-21 09:46 UTC, closed without merging