WIP: Task 1 - inport exception handle
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #67
Opened 2020-11-12 08:20 UTC by kaplonpaulina

2020-11-12 16:45 UTC, Qwebeck requested changes
Najważnniejsze - to dodać ustawienie grafiku customowej flagi na grafiku w momencie kiedy wykrywamy błędy ( lub obsłużyć to w jakiś inny sposób), usunąc pushowanie błędów do stanu i poprawić literówkę w todo ( masz `dsplay`, zamiast `display` )   ( jbc, to żartuję i todo można nie poprawiać 😄 )
Byłoby też super dodać inne poprawki o których pisałem.  

Potrzeba też usunąc `==`, ponieważ pojawiją się warningi w konsoli 
![image](https://user-images.githubusercontent.com/21079319/98967679-0c886500-250d-11eb-8136-a8637a702a50.png)

2020-11-12 16:45 UTC, Qwebeck commented on src/components/toolbar/import-buttons/hooks/use-schedule-converter.ts
> +          actual: e.message,
Tak naprawdę, to mogą pojawić się nie tylko te wyjątki które wyrzucamy my. Może też być tak, że będzie `IndexOutOfRange`, `Property of undefined`, etc. 
I w obecnej implementacji my pokazalibyśmy te wyjątki użytkownikowi. Więc moim zdaniem, lepiej by było:

1. Zdefiniować wiecej pół w enumie `SectionParserError`: LOST_CHILDREN_SECTION, LOST_NURSE_SECTION, etc. 
2. Po takim zhandlowaniu jak tutaj, ustawiać `{ code : e.message }` który ty dodajesz. 
3. Zmodyfikować `ErrorMessageHelper` tak, żeby on obsługiwał te wyjątki, co będą w enumie i zwracał do każdego z nich odpowiednią wiadomość. I to miało by taki sens, że w unikamy tego problemu z wyjątkami które nie są czytelne dla nas. 

Odnośnie `Actual` - to ja źle zrobiłem. To customowe pole dla handlowania niedozwolonych symboli w grafiku Potrzeba by było zaimplementować to inaczej w taki sposób, żeby było mapowanie 1:1 -- Enum z kodami wyjątków, struktura wyjątku. ( nie koniecznie w tym  PR ). 
```typescript
export type ParserError = UnknownValueError | InputFileError;
interface UnknownValueError {
  code: ParseErrorCode.UNKNOWN_VALUE
  actual: string;
}
interface InputFileError {
  code: ParseErrorCode.INPUT_FILE_ERROR // ew. ParseErrorCode.LOST_NURSE_SECTION | ParseErrorCode.LOST_CHILDREN_SECTION ...
  missingSection: string;
}
```

I wtedy to by było mega, ponieważ dla każdego kodu wyjątku moglibyśmy mieć specyficzne pola:
![image](https://user-images.githubusercontent.com/21079319/98965503-6d626e00-250a-11eb-986c-bfaed84aebdd.png)
Zauważ, że mimo tego, że podałem typ error jako `ParserError` jako `UnknownValueError | InputFileError`, typescript wywnioskował na podstawie pola `code` o którym dokładnie interfejsie chodzi i podpowiada mi brakujące pole z  interfejsu `UnknownValueError`.

@Sig00rd , jak byś chciał, to mógłbyś też przerobić wyjątki od algorytmu na taką postać :D 
Bo kiedy mnie pytałeś o tym jak to najlepiej zrobić, to nie wiedziałem, że coś takiego istnieje.

2020-11-12 16:45 UTC, Qwebeck commented on src/components/toolbar/import-buttons/import-buttons.component.tsx
> +    } else {
Potrzeba będzie zamienić ten warunek co jest w if (26 linijka) na jakąś customową flagę, która pozwala sprawdzić czy grafik jest wczytany poprawnie.  
I ustawić to w catch.
![image](https://user-images.githubusercontent.com/21079319/98966580-bc5cd300-250b-11eb-89f8-008206d0d9e1.png)

Bo teraz wchodzimy w elese w momencie odpalenia aplikacji

![image](https://user-images.githubusercontent.com/21079319/98968873-8ec55900-250e-11eb-9493-0ee2e3a214b3.png)

PS. display message - to `console.log` który dodałem w tym elsie

2020-11-16 19:30 UTC, Qwebeck commented on src/common-models/schedule-error.model.ts
> +export type ParserError = UnknownValueError | InputFileError | AlgorithmError;
ScheduleErorro

2020-11-16 19:35 UTC, Qwebeck commented on src/components/toolbar/import-buttons/hooks/use-schedule-converter.ts
> +        setErrorOccurredFlag(true);
Poprawić na ScheduleErrorCode

2020-11-16 22:07 UTC, Sig00rd commented
Imo może być ten ParserError tylko wtedy myślę, że pasowałoby zmienić nazwę pliku na parser-error.model. Jeden problem jaki znalazłem to że jak ładuję grafik z pustą sekcją dzieci albo bez tej sekcji to nie wyrzuca się odpowiedni error tylko ładuje się grafik z pustą sekcją dzieci, sprawdzaliście taki przypadek?

2020-11-17 19:53 UTC, kaplonpaulina commented
> Imo może być ten ParserError tylko wtedy myślę, że pasowałoby zmienić nazwę pliku na parser-error.model. Jeden problem jaki znalazłem to że jak ładuję grafik z pustą sekcją dzieci albo bez tej sekcji to nie wyrzuca się odpowiedni error tylko ładuje się grafik z pustą sekcją dzieci, sprawdzaliście taki przypadek?

Hmm, u mnie jak usuwam dzieci dostaję error. Podrzuciłbyś plik, którego użyłeś?

2020-11-17 20:22 UTC, kaplonpaulina commented on src/components/toolbar/import-buttons/import-buttons.component.tsx
> +      type: ScheduleErrorActionType.UPDATE,
w innym MR, ten jest już stanowczo za duży

2020-11-18 10:52 UTC, kaplonpaulina commented
> Imo może być ten ParserError tylko wtedy myślę, że pasowałoby zmienić nazwę pliku na parser-error.model. Jeden problem jaki znalazłem to że jak ładuję grafik z pustą sekcją dzieci albo bez tej sekcji to nie wyrzuca się odpowiedni error tylko ładuje się grafik z pustą sekcją dzieci, sprawdzaliście taki przypadek?

ok, dodałam wyjątki na wszystko co mi przyszło do głwy,
Będę wdzięczna za pomoc w testowaniu

2020-11-19 21:31 UTC, Qwebeck commented on src/common-models/schedule-error.model.ts
> +  NO_CARETAKER_SECTION = "noCaretakerSection",
Wszędzie w aplikacji tłumaczymy słowo opiekunka jako `babysitter`, więc może mogłabyś to zmienić, żeby nie wprowadzać zamieszania

2020-11-19 22:16 UTC, Qwebeck commented on src/components/toolbar/import-buttons/hooks/use-schedule-converter.ts
> +      throw new Error("EMPTY_FILE");
Ja bym użył w tym miejscu `enum`. 
I zminiełbym ten enum co ty zrobiłaś zmieniłbym w taki sposób, że wartości będą takie same jak klucze. 
Czyli:
```typescript
export enum InputFileErrorCode {
  EMPTY_FILE = "EMPTY_FILE",
  NO_CARETAKER_SECTION = "NO_CARETAKER_SECTION",
  NO_NURSE_SECTION = "NO_NURSE_SECTION",
  NO_CHILDREN_SECTION = "NO_CHILDREN_SECTION",
  INVALID_METADATA = "INVALID_METADATA",
  NO_CHILDREN_QUANTITY = "NO_CHILDREN_QUANTITY",
}
```

2020-11-19 22:17 UTC, Qwebeck commented on src/components/toolbar/import-buttons/hooks/use-schedule-converter.ts
> +      throw new Error("EMPTY_FILE");
I to było by fajne pod tym względem, że trudniej by było się pomylić (np. zrobić literówkę ) przy wyrzuceniu wyjątku z kodem.

2020-11-19 22:22 UTC, Qwebeck commented on src/logic/schedule-parser/schedule.parser.ts
> +      MetaDataSectionKey.Month + " [" + Object.values(MONTHS).join("|") + "]"
Super to zrobiłaś :D

2020-11-19 22:24 UTC, Qwebeck commented on src/logic/schedule-parser/schedule.parser.ts
> +export enum MONTHS {
Mamy już coś podobnego. 
`nurse-scheduling-problem-frontend/src/helpers/tranlsations.helper.ts`
```
      styczeń: "january",
      luty: "february",
      marzec: "march",
      kwiecień: "april",
      maj: "may",
      czerwiec: "june",
      lipiec: "july",
      sierpień: "august",
      wrzesień: "september",
      październik: "october",
      listopad: "november",
      grudzień: "december",
```
Więc proponuję lub zamienić we wszystkich miejscach w których używamy tego obiektu, użyć enum który napisałaś ty, lub w tym miejscu użyć tego obiektu.
 Jbc, to mi odpowiadają obie opcje ;)

2020-11-19 22:26 UTC, Qwebeck requested changes
Tylko te drobne poprawki o których pisałem, a tak to jest naprawdę super :D

2020-11-21 10:28 UTC, kaplonpaulina reviewed
LGTM

2020-11-21 11:32 UTC, Qwebeck approved these changes

2020-11-21 11:43 UTC, merged