TASK-9 Introduce React Router
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #70
Opened 2020-11-18 18:07 UTC by Sig00rd

Dodałem React Router i przykładowe podstrony żeby można było zobaczyć jak się robi routing i linkowanie (finalnie do wywalenia / zmiany na odpowiednie ofc).
Nie wrzucałem komponentów związanych z widokiem grafiku do katalogu schedule-page (chociaż tak wydaje mi się sensownie byłoby trzymać kod jak tych podstron dojdzie) bo chciałbym najpierw usłyszeć wasze zdanie nt. organizacji kodu tam, więc proszę o komentarz

2020-11-18 23:32 UTC, Qwebeck commented on src/components/dummy-page/dummy-page.component.tsx
> +export default function DummyPage(): JSX.Element {
W związku z wprowadzeniem stron, proponuję nieco zupdatować strukturę katalogu w taki sposób, że komponenty będą pogrupowane w foldery stron do który należą ( lub będą w folderze common components ). Czyli:
```
components
|
`schedule-page
      |
      `table
      |
      `validation-drawer
     |
     ` import-buttons
     |
     `problem-metadata
|
`workers-page
```
Umyślnie nie pogrupowałem validation-drawer, import-buttons, problem-metadata do folderu `toolbar`, bo myślę, że ten folder można by było usunąć
@pectom , co o tym sądzisz?

2020-11-19 13:50 UTC, pectom commented on src/components/dummy-page/dummy-page.component.tsx
> +export default function DummyPage(): JSX.Element {
Zgadzam się z @Qwebeck. Super by było, gdybyś @Sig00rd wprowadził to w tym PR

2020-11-19 19:27 UTC, Sig00rd commented
Zrobiłem wg ustaleń, zerknijcie proszę czy wszystko jest po bożemu bo ze zmianami z ostatniego developa wyszedł merdżas wielgas i nie jestem pewien czy wszystko pomergowałem jak trzeba

2020-11-19 21:08 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/schedule-row.component.tsx
> +import React, { useCallback, useContext, useEffect, useMemo, useState } from "react";
Tego pliku nie musi być. Zmieniliśme jego nazwę na base-row.component, bo taka jest o wiele bardziej sensowna :D 
Sprawdzałem i u ciebie na branchu też jest ten plik, więc jedyne co potrzeba zrobić- to usunąc `schedule-row.component`
![image](https://user-images.githubusercontent.com/21079319/99724280-af178980-2ab3-11eb-88f2-83a10b37be28.png)

2020-11-19 21:10 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule-parts/empty-row.component.tsx
> +import React from "react";
Do usunięcia plik `empty-cell.component`
![image](https://user-images.githubusercontent.com/21079319/99724480-f271f800-2ab3-11eb-8bb1-5ed3d98f296c.png)

2020-11-19 21:12 UTC, Qwebeck reviewed
Do usunięcia plik `empty-cell.component`
![image](https://user-images.githubusercontent.com/21079319/99724480-f271f800-2ab3-11eb-8bb1-5ed3d98f296c.png)

Zostawiam to w tym miejscu, ponieważ  nie niestety mogę zostawić komentarz pod `empty-cell.component`


Też myślę, że takie komponenty jak `add-worker-modal oraz global components można by było pogrupować do pliku `common-components`
![image](https://user-images.githubusercontent.com/21079319/99724886-9491e000-2ab4-11eb-8542-4d0edf7cc9cc.png)

2020-11-20 14:54 UTC, pectom requested changes
Popieram @Qwebeck w kwestii przerzucenia rzeczy do common componentów. Fajnie, gdyby ten folder powstał, żeby przy tworzeniu nowych rzeczy inne osoby wiedziały, że można tam wrzucać rzeczy, które będą się powtarzać. Tylko, że to zadanie zamienia nam się coraz bardziej w refactor, a tego mamy unikać. Dlatego trzeba to jak najszybciej zmergować, żeby nowe zadania wychodziły już od tej struktury. 
Druga kwestia jest taka, że wywala nam się test, więc to jeszcze trzeba poprawić.

2020-11-20 15:02 UTC, Qwebeck commented
> 
> 
> Popieram @Qwebeck w kwestii przerzucenia rzeczy do common componentów. Fajnie, gdyby ten folder powstał, żeby przy tworzeniu nowych rzeczy inne osoby wiedziały, że można tam wrzucać rzeczy, które będą się powtarzać. Tylko, że to zadanie zamienia nam się coraz bardziej w refactor, a tego mamy unikać. Dlatego trzeba to jak najszybciej zmergować, żeby nowe zadania wychodziły już od tej struktury.
> Druga kwestia jest taka, że wywala nam się test, więc to jeszcze trzeba poprawić.

Tak, to jest dziwne.
Jeszcze dziwniejsze jest to, że ten test nie przechodzi na 4 z 6 merge requestów
![obraz](https://user-images.githubusercontent.com/21079319/99814855-d9b42180-2b49-11eb-9497-d6b019e6cc9b.png)

2020-11-20 16:11 UTC, Sig00rd commented
Poprawione, po naradzie z Tomkiem wrzuciłem też do common components snackbar.
Testu nie ruszałem bo manualny test tego scenariusza przechodzi i szczerze mówiąc jak przejrzałem kod związany z testem to nie wiem co jest źle

2020-11-21 12:48 UTC, Qwebeck approved these changes

2020-11-21 12:49 UTC, merged