TASK-30 Header
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #76
Opened 2020-11-23 19:37 UTC by VVlovsky

Podstawowa implementacja headeru + routing na workers.
![image](https://user-images.githubusercontent.com/36051968/100005436-9f5cb580-2dd1-11eb-9656-7d3ae21502e6.png)

2020-11-23 23:18 UTC, Sig00rd commented on src/components/common-components/header/header.tsx
> +            <Link to="/workers/">Zażądzanie</Link>
Zarządzanie

2020-11-24 00:18 UTC, VVlovsky commented on src/components/common-components/header/header.tsx
> +            <Link to="/workers/">Zażądzanie</Link>
Dziękuję, poprawiłem

2020-11-24 02:44 UTC, Qwebeck commented on src/assets/styles/styles/custom/_header.scss
> +  background-color: #1d3557;
Kolor lepiej wynieść do zmiennej, ponieważ używamy go też w innych miejscach: 
![image](https://user-images.githubusercontent.com/21079319/100040331-57f11c00-2e07-11eb-8c51-ce7619f68388.png)

2020-11-24 02:56 UTC, Qwebeck commented on src/components/common-components/header/header.tsx
> +        <img src={require("../../../assets/images/header-logo.png")} title={""} alt={""} />
Zamiast plików png lepiej używać svg, ponieważ one są skalowalne w odróźnieniu od png. Ponadto mają taką zaletę, że łatwiej jest ich używać: wszystko sprowadza się do instalacji biblioteki i użycia tega odpowiedniej ikonki.

2020-11-24 03:10 UTC, Qwebeck commented on src/components/common-components/header/header.tsx
> +            <Link to="/">Raporty</Link>
Myślę, że lepiej nie dodawać ścieżki do raportów, ponieważ ona teraz nigdzie nie prowadzi.

2020-11-24 03:13 UTC, Qwebeck requested changes
Naprawdę super to wygląda !
Świetna praca :D 
Request changes, ponieważ po dzisiejszym spotkaniu z Agą pojawiło się kilka zmian w nagłówku które potrzeba będzie wprowadzić ( nie są drastyczne, więc myślę, że nie będzie to dużym problemem ). Przegadamy to na stanup'ie

2020-11-24 03:15 UTC, Qwebeck commented on src/components/schedule-page/schedule-page.component.tsx
> +        <Header />
Próbowałeś dodać ten komponent w `app.tsx`? 
Odrazu na `ReactRouter`. 
Mi się wydaje, że wtedy to też będzie działać, ale będzie miało taką zaletę, że nagłówek będzie odrazu dodany do wszystkich stron

2020-11-24 12:19 UTC, Dushess0 approved these changes

2020-11-26 22:54 UTC, Qwebeck approved these changes

2020-11-26 22:55 UTC, merged