Task 66
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #78
Opened 2020-11-24 15:52 UTC by Dushess0

Dodałem  sekcję, która zawiera informację o:
- liczbie dzieci
- liczbie pielęgniarek i opiekunek (dodać zamiast pracownicy)
- liczbie pracowników dziennych
Narazie dane są zamockowane
![image](https://user-images.githubusercontent.com/44201461/100117531-2f077000-2e75-11eb-93a5-50685adff89c.png)

2020-11-24 16:09 UTC, Qwebeck commented
@pectom 
@Dushess0 robił to razem ze mną, więc większość usunięć z kodu była przekonsultowana. Teraz jeszcze pododaję komentarze w tych miejscach.

2020-11-24 16:10 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule.component.tsx
> +              <ShiftInfoSectionComponent
Zmienić nazwę na `FoundationInfo`

2020-11-24 16:10 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/schedule.component.tsx
> +              <ShiftInfoSectionComponent
Bo to faktycznie informacja o całym ośrodku, a nie o zmianach

2020-11-24 16:13 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/use-schedule-state.ts
> -        childrenSection: (scheduleLogic.sections.ChildrenInfo as ChildrenInfoLogic).sectionData,
Połączylismy te dwie sekcje w sekcję `foundationInfoSection`

2020-11-24 16:17 UTC, Qwebeck commented on src/logic/providers/foundation-info-provider.model.ts
> +}
@pectom 
Korzystamy z tych providerów co już były, żeby nie zmieniać za dużo kodu.
`ExtraWorkersInfo`, `ChildrenInfo` - potrzebne żeby wyświetlić informację o dzieciach i pracownikach dodatkowych. 
Natomiast `ShiftInfoProvider` my potrzebujemy ponieważ ponieważ chcemy móc wyliczyć liczbę pracowników w odpowiednich dniach

2020-11-24 16:24 UTC, Qwebeck commented on src/logic/providers/foundation-info-provider.model.ts
> +export interface FoundationInfoOptions {
Ja bym uzależnił to od interfesju `Sections`. 
Czyli coś w stylu:
```
interface FoundationInfoOptions extends Pick<Sections, "NurseInfo" | "BabysitterInfo"> {
  ChildrenInfo: ChildrenInfoProvider; 
   ExtraWorkersInfo: ExtraWorkersInfoProvider;
}
```
https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys

2020-11-24 16:31 UTC, Qwebeck commented on src/logic/schedule-logic/children-info.logic.ts
> -export class ChildrenInfoLogic extends BaseSectionLogic implements ChildrenInfoProvider {
@pectom 
Usunęliśmy dziedziczenie po `BaseSectionLogic`, ponieważ `BaseSectionLogic` wymaga `sectionKey`, który musi należeć do interfejsu `Sections`. A do tego interfejsu z zalożenia należą tylko te sekcje, co są widoczne.

 Nie mniej jednak, myśle, że potrzeba będzie w jakiś sposób to przekminić, ponieważ `BaseSectionLogic` ma metodę `updateSection`, a my czasami chcemy zmieniać liczbę dzieci i było by fajnie użyć metody która jest zdefiniowana na `BaseSectionLogic` zamiast duplikować kod.

2020-11-24 16:42 UTC, Qwebeck commented on src/logic/schedule-logic/foundation-info.logic.ts
> +    throw new Error("Method not implemented.");
@pectom 
Nie używamy logiki z `BaseSectionLogic`, ponieważ nie wszystkie wiersze możemy edytować ( tylko `childrenInfo`), więc potrzeba to jakoś dostoswać

2020-11-24 17:02 UTC, Qwebeck commented on src/logic/section.model.ts
> +export class FoundationSectionKey {
Klasa, ponieważ chcieliśmy wykorzystać klucze z innego enuma, a VS Code wyrzucał ostrzeżenie o tym, że nie da się tego zrobić.  Ale okazuję się, że da:
![image](https://user-images.githubusercontent.com/21079319/100127135-1734e980-2e7f-11eb-94b0-2af94625f68b.png)

Więc można było by to zbadać. Można też zostawić tak jak jest, bo osobiście mi to nie za bardzo przeszkadza.

2020-11-24 21:30 UTC, Qwebeck commented on src/components/schedule-page/table/schedule/sections/shift-info-section/shift-info-section.components.tsx
> +export type ExtraWorkersSectionOptions = BaseSectionOptions;
To nie jest używane

2020-11-24 21:35 UTC, Qwebeck commented on src/helpers/array.helper.ts
> +    return Array.from(Array(count)).map((x) => element | 0);
Ten pipe nie może zostać
![image](https://user-images.githubusercontent.com/21079319/100153862-05fed380-2ea5-11eb-8e95-224b64cc5536.png)

Lepiej użyć ??, bo typescript to lepiej obsługuje
![image](https://user-images.githubusercontent.com/21079319/100154030-49594200-2ea5-11eb-8f28-423ef1d7b428.png)

2020-11-24 21:53 UTC, pectom requested changes

2020-11-24 21:53 UTC, pectom commented on src/logic/providers/foundation-info-provider.model.ts
> +      7
Do zupdateowania po PR-61 od @Dimonium-239

2020-11-26 19:21 UTC, Dushess0 commented on src/logic/providers/foundation-info-provider.model.ts
> +      7
zrobione

2020-11-26 19:22 UTC, Dushess0 commented
Poprawiłem to co było powiedziane, proszę jeszcze raz zerknąć na kod

2020-11-26 19:58 UTC, Qwebeck commented on src/logic/providers/foundation-info-provider.model.ts
>    getWorkersCount(workerType: WorkerType): number[] {
Ja bym usunął ten argument, bo on nie jest używany

2020-11-27 09:49 UTC, pectom approved these changes

2020-11-27 14:44 UTC, Dushess0 commented on src/logic/providers/foundation-info-provider.model.ts
>    getWorkersCount(workerType: WorkerType): number[] {
zrobione

2020-11-27 16:10 UTC, Qwebeck approved these changes

2020-11-27 16:13 UTC, merged