Task 116 work hour calculation
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #92
Opened 2020-11-29 04:41 UTC by Qwebeck

Dodam jeszcze test do tego, ale nie wcześniej niż w poniedziałek, więc myślę, że żeby nie zatrzymywać @Sig00rd można zmergować to w takim stanie.

2020-11-29 04:46 UTC, Qwebeck commented on src/helpers/shifts.helper.ts
> +    return [requiredHours, actualHours, overtime];
@pectom , @prenc   zerknijcie proszę na to. 
Logika jest taka, że najpierw szukamy pierwszy dzień miesiąca, któryjest potrzebny żeby wybrać aktualne zmiany, potem szukamy w tych zmianach wszystkie dni w których da się pracować ( nie święto, nie weekend, nie U,  nie L4 ). 
Na podstawie tych dni oraz etatu, liczymy normę. 
![image](https://user-images.githubusercontent.com/21079319/100533515-a2a6d580-3205-11eb-8abb-22b06d0574e6.png)

2020-11-30 03:34 UTC, pectom requested changes
Moim zdaniem powinniśmy w tym tasku od razu dopiąć sprawę edycji pól z godzinami, bo obecnie taka próba kończy się błędem i wolałbym żebyśmy tego nie mergowali:
![image](https://user-images.githubusercontent.com/23723122/100565977-152aba80-32c5-11eb-8d84-5d60af750735.png)
Chyba, że okaże się to pracochłonne i @Sig00rd będzie potrzebował tego w najbliższym czasie to możemy to domergować i wystawić buga

2020-11-30 09:15 UTC, prenc requested changes
Chciałbym zrobić review, ale w ogóle nie działa sprawdzanie z serwera (może coś źle robię)
![image](https://user-images.githubusercontent.com/26227269/100590373-9b122a00-32f4-11eb-90ba-81b6b300f15b.png)
Ewaluacja samych godzin wygląda, że dobrze poprawnie.

2020-12-01 00:08 UTC, Qwebeck commented
> Moim zdaniem powinniśmy w tym tasku od razu dopiąć sprawę edycji pól z godzinami, bo obecnie taka próba kończy się błędem i wolałbym żebyśmy tego nie mergowali:
> ![image](https://user-images.githubusercontent.com/23723122/100565977-152aba80-32c5-11eb-8d84-5d60af750735.png)
> Chyba, że okaże się to pracochłonne i @Sig00rd będzie potrzebował tego w najbliższym czasie to możemy to domergować i wystawić buga

Słusznie, ale zaczekam do momentu, aż @kaplonpaulina wrzuci te zmiany co ona robiła z tabelką, bo może być tak, że to już jest poprawione tam.

2020-12-01 00:10 UTC, Qwebeck commented
> Jednak źle działa, święta i weekendy są dniami pracującymi.
> 
> Chciałbym zrobić review, ale w ogóle nie działa sprawdzanie z serwera (może coś źle robię).
> ![image](https://user-images.githubusercontent.com/26227269/100590373-9b122a00-32f4-11eb-90ba-81b6b300f15b.png)

Słabo, że to tak wygląda. 
Postaram się zobaczyć co jest nie tak przed spotkaniem.

2020-12-01 03:49 UTC, Qwebeck commented on src/api/backend.ts
> +interface BackendErrorObject extends Omit<ScheduleError, "kind"> {
Nie dawno temu zmienialiśmy interfejs który opisuje błędy i zapomnieliśmy dodać mapowanie przy odpowiedzi z serwera.
Dodałem i w taki sposób poprawiłem bug z `UnknownError`
![image](https://user-images.githubusercontent.com/21079319/100695009-969b4f00-3390-11eb-83b2-04f6a5a0c8c8.png)

2020-12-01 04:01 UTC, Qwebeck commented
Zrobiełm force-update, bo zauważyłem, że na branchu pojawił się jeden nie potrzebny commit, który kiedyś robilem, żeby móc przełączyć się na inny branch i nie stracić tego co napisałem

2020-12-01 04:32 UTC, Qwebeck commented
> 
> 
> Jednak źle działa, święta i weekendy są dniami pracującymi.
> 
> Chciałbym zrobić review, ale w ogóle nie działa sprawdzanie z serwera (może coś źle robię).
> ![image](https://user-images.githubusercontent.com/26227269/100590373-9b122a00-32f4-11eb-90ba-81b6b300f15b.png)

Może być tak, że aktualne godziny są źle liczone na serwerze, ponieważ my wysyłamy też dni z poprzedniego miesiąca, które on nie musi uwzględniać. Ponadto na serwerze pewno nie są uwzględniane święta.

Bo zobacz jak to wygląda dla pielęgniarki 2
![image](https://user-images.githubusercontent.com/21079319/100697493-6fe01700-3396-11eb-994f-a4fde7b8188d.png)
```
// Aktualne
// D + R + N + D + 2 * N + DN + 4*N + D + 2*N + D + DN + PN + DN
// 12+8+12+12+24+24+48+12+24+12+16+24+12=240
  public static shiftCodeToWorkTime(shiftCode: ShiftCode): number {
    switch (shiftCode) {
      case ShiftCode.R:
        return 8;
      case ShiftCode.P:
        return 4;
      case ShiftCode.D:
        return 12;
      case ShiftCode.N:
        return 12;
      case ShiftCode.DN:
        return 24;
      case ShiftCode.PN:
        return 16;
      default:
        return 0;
    }
  }
```
Wymagane:
liczba dni które nie są świętami i nie są weekendami * etat * 8:
8 * 21 = 168

I wtedy nadgoziny wychodzą:
240 - 168 = 72

Natomiast algorytm zwraca: 30
![image](https://user-images.githubusercontent.com/21079319/100697399-314a5c80-3396-11eb-849e-75c4af2d75df.png)

2020-12-01 21:12 UTC, Sig00rd approved these changes

2020-12-01 22:22 UTC, prenc requested changes
![image](https://user-images.githubusercontent.com/26227269/100803497-8c7a5e80-342b-11eb-8fc6-2edcb6dd0fa2.png)

Według mnie nie jest poprawnie. Trzeba rozpatrywać tygodniowo i liczyć, że maks w przeciągu tygodnia może być za 5 dni. Na obrazku ktoś zobie wziął urlop na weekend i mu nie zmniejszyło godzin które ma wyrobić. Zamiast -40 powinno być -24. Tak działą algorytm, przynajmniej tak powinien działać xD

2020-12-01 23:33 UTC, Qwebeck commented
> 
> 
> ![image](https://user-images.githubusercontent.com/26227269/100803497-8c7a5e80-342b-11eb-8fc6-2edcb6dd0fa2.png)
> 
> Według mnie nie jest poprawnie. Trzeba rozpatrywać tygodniowo i liczyć, że maks w przeciągu tygodnia może być za 5 dni. Na obrazku ktoś zobie wziął urlop na weekend i mu nie zmniejszyło godzin które ma wyrobić. Zamiast -40 powinno być -24. Tak działą algorytm, przynajmniej tak powinien działać xD

Czyli ty proponujesz zrobić tak, że na każdy 7 dni pracownik musi odpracować (5 - ilość świąt) * etat

2020-12-01 23:50 UTC, prenc commented
@Qwebeck no według mnie tak to powinno wyglądać, tak działa algorytm i chyba tak kiedyś ustaliłem z Mateuszem, ale dla pewności można poruszyć na spotkaniu piątkowym

2020-12-03 23:04 UTC, Qwebeck commented
> 
> 
> @Qwebeck no według mnie tak to powinno wyglądać, tak działa algorytm i chyba tak kiedyś ustaliłem z Mateuszem, ale dla pewności można poruszyć na spotkaniu piątkowym

https://docs.google.com/spreadsheets/d/17V_nDtFy_TKiz6cN6U02jDb8hKm_62lU/edit#gid=351303914

Dodałem testy na rzeczywistym grafiku i wygląda na to, że dobrze liczę. 
Testowałem dla Pielęgniarki 3

2020-12-03 23:05 UTC, Qwebeck commented
> Fix how overtime is calculated
@Sig00rd , z czym jest problem?

2020-12-04 12:44 UTC, prenc approved these changes
Wszystko git

2020-12-04 12:47 UTC, pectom approved these changes

2020-12-04 12:47 UTC, merged