TASK-112
Project-Summer-AI-Lab-Glider/nurse-scheduling-problem-frontend pull request #93
Opened 2020-11-29 15:21 UTC by Dushess0

workerCount are now using different data for nurses and babysitters. Removed error from route-buttons.component. Fixed missed columns in getWorkersCount in shifts.helper.ts

fixed table:
![image](https://user-images.githubusercontent.com/44201461/100545939-d3672900-325e-11eb-8858-ec9aa0d709fc.png)

2020-11-29 22:44 UTC, Qwebeck requested changes
Brakuje testów do funkcji `ShiftHelper.getWorkersCount`. Testy co były przed tym można usunąć, ponieważ nie sprawdzały działania tej funkcji: zmieniłeś logikę a one nadal przechodzą.

2020-11-30 15:04 UTC, VVlovsky commented
> Brakuje testów do funkcji `ShiftHelper.getWorkersCount`. Testy co były przed tym można usunąć, ponieważ nie sprawdzały działania tej funkcji: zmieniłeś logikę a one nadal przechodzą.

Czyli testy nie muszą isć jako osobny task?

2020-11-30 15:19 UTC, Qwebeck commented
> 
> 
> > Brakuje testów do funkcji `ShiftHelper.getWorkersCount`. Testy co były przed tym można usunąć, ponieważ nie sprawdzały działania tej funkcji: zmieniłeś logikę a one nadal przechodzą.
> 
> Czyli testy nie muszą isć jako osobny task?

Testy idą jako osobny task tylko do starej funkcjonalności, która jeszcze nie była przetestowana.
Ponadto w tym zadaniu jest taki problem, że testy już były napisane, ale nie sprawdzały działanie tej funkcjonalności. 
Więc potrzeba je poprawić zanim to będzie zmergowane

2020-12-05 02:35 UTC, Qwebeck approved these changes

2020-12-05 02:37 UTC, merged